# generated by datamodel-codegen:
#   filename:  virtmcu_world.schema.json
#   timestamp: 2026-05-03T03:21:48+00:00

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class Model(RootModel[Any]):
    root: Any
