# generated by datamodel-codegen:
#   filename:  world_schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint, constr


class Model(RootModel[Any]):
    root: Any


class Cpu(BaseModel):
    name: str
    type: str
    memory: str | None = None
    isa: str | None = None
    mmu_type: str | None = None


class Address(RootModel[conint(ge=0) | constr(pattern=r'^0x[0-9a-fA-F]+$')]):
    root: conint(ge=0) | constr(pattern=r'^0x[0-9a-fA-F]+$')


class RecordUnknown(BaseModel):
    pass


class Transport(Enum):
    zenoh = 'zenoh'
    unix = 'unix'


class Role(Enum):
    Cyber = 'Cyber'
    Physics = 'Physics'


class NodeID(RootModel[conint(ge=0) | str]):
    root: conint(ge=0) | str


class Protocol(
    RootModel[
        constr(
            pattern=r'^(Ethernet|Uart|CanFd|Spi|FlexRay|Lin|Rf802154|RfHci|eth|uart|canfd|spi|flexray|lin|rf802154|rfhci)$'
        )
    ]
):
    root: constr(
        pattern=r'^(Ethernet|Uart|CanFd|Spi|FlexRay|Lin|Rf802154|RfHci|eth|uart|canfd|spi|flexray|lin|rf802154|rfhci)$'
    ) = Field(..., description='Supported inter-node communication protocols.')


class Coordinate(BaseModel):
    x: float
    y: float
    z: float


class Machine(BaseModel):
    name: str | None = None
    type: str | None = None
    cpus: list[Cpu] | None = None


class Resource(BaseModel):
    name: str
    type: str | None = None
    renode_type: str | None = None
    address: Address | None = None
    size: Address | None = None
    parent: str | None = None
    container: str | None = None
    interrupts: list[str | int] | None = None
    properties: RecordUnknown | None = None


class Node(BaseModel):
    name: NodeID
    role: Role | None = None


class WireLink(BaseModel):
    type: Protocol
    nodes: list[NodeID]
    baud: conint(ge=0, le=4294967295) | None = None


class WirelessNode(BaseModel):
    name: NodeID
    initial_position: Coordinate


class WirelessMedium(BaseModel):
    medium: str
    max_range_m: float
    nodes: list[WirelessNode]


class Topology(BaseModel):
    nodes: list[Node] | None = None
    links: list[WireLink] | None = None
    wireless: WirelessMedium | None = None
    global_seed: str | None = None
    transport: Transport | None = None
    max_messages_per_node_per_quantum: conint(ge=0, le=4294967295) | None = None


class WorldSchema(BaseModel):
    machine: Machine | None = None
    peripherals: list[Resource] | None = None
    memory: list[Resource] | None = None
    topology: Topology | None = None
    nodes: list[Node] | None = None


class World(BaseModel):
    machine: Machine | None = None
    peripherals: list[Resource] | None = None
    memory: list[Resource] | None = None
    topology: Topology | None = None
    nodes: list[Node] | None = None
