#!/usr/bin/env python3
# ==============================================================================
# apply_zenoh_hook.py
#
# Inject a TCG quantum hook into QEMU's cpu-exec.c.
#
# QEMU does not expose a native plugin API to hook into the main translation
# block (TB) execution loop (`cpu_exec`). In order to allow external QOM modules
# (like the zenoh clock sync from FirmwareStudio) to cooperatively halt QEMU
# at translation block boundaries, we must inject a global function pointer.
#
# This script is idempotent: it parses `accel/tcg/cpu-exec.c`, finds the
# execution loop, and safely AST-injects a call to `virtmcu_tcg_quantum_hook`.
# ==============================================================================

import os
import sys


def write_if_changed(path, content):
    """Write content to path only if it differs. Returns True if written."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path):
        with open(path) as f:
            if f.read() == content:
                return False
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {os.path.relpath(path)}")
    return True


def patch_file(path, marker, insertion, after=True):
    with open(path) as f:
        content = f.read()
    if marker not in content:
        print(f"  WARNING: marker not found in {os.path.relpath(path)}: {marker!r}")
        return False

    # If the exact insertion is already there, we are done.
    if insertion.strip() in content:
        return False

    # If a DIFFERENT version of the virtmcu hook is there, remove it first.
    # We identify our hooks by the "virtmcu_" prefix in the function/variable names.
    # This is a bit hacky but works for our specific hooks.
    # Try to find if we already patched this file near the marker.
    # For simplicity, if we find "virtmcu_" followed by the hook name in the file,
    # and it's NOT the exact insertion, we might want to replace it.
    # But replacing is hard with regex if it's multi-line.
    # Use a unique tag for each patch based on the marker.
    import hashlib
    import re

    marker_hash = hashlib.md5(marker.encode()).hexdigest()[:8]
    tag = f"/* VIRTMCU_PATCH_{marker_hash} */"
    tagged_insertion = f"\n{tag}{insertion}{tag}\n"

    if tagged_insertion.strip() in content:
        return False

    # Remove old tagged insertions if they exist
    pattern = re.escape(tag) + r".*?" + re.escape(tag)
    if re.search(pattern, content, re.DOTALL):
        new_content = re.sub(pattern, tagged_insertion.strip(), content, flags=re.DOTALL)
        if new_content == content:
            return False
        content = new_content
        print(f"  updated patch in {os.path.relpath(path)} (marker={marker_hash})")
    else:
        if after:
            new_content = content.replace(marker, marker + tagged_insertion, 1)
        else:
            new_content = content.replace(marker, tagged_insertion + marker, 1)

        if new_content == content:
            return False
        content = new_content
        print(f"  patched {os.path.relpath(path)} (marker={marker_hash})")

    with open(path, "w") as f:
        f.write(content)
    return True


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <qemu-source-dir>")
        sys.exit(1)

    qemu = os.path.abspath(sys.argv[1])

    # 1. Create include/virtmcu/hooks.h
    hooks_h = os.path.join(qemu, "include", "virtmcu", "hooks.h")

    hooks_h_content = """/* Generated by apply_zenoh_hook.py */
#ifndef VIRTMCU_HOOKS_H
#define VIRTMCU_HOOKS_H

#include "hw/core/cpu.h"
#include "net/net.h"

/*
 * Timing constraints exported to Sensor/Actuator Abstraction Layers (SAL/AAL).
 * Used to align physics interpolation with virtual execution time.
 */
typedef struct {
    int64_t quantum_start_vtime_ns;
    int64_t quantum_delta_ns;
    int64_t mujoco_time_ns;
} VirtmcuQuantumTiming;

extern void (*virtmcu_tcg_quantum_hook)(CPUState *cpu);
extern int (*virtmcu_zenoh_netdev_hook)(const Netdev *netdev, const char *name, NetClientState *peer, Error **errp);
extern void (*virtmcu_irq_hook)(void *opaque, int n, int level);
extern void (*virtmcu_cpu_halt_hook)(CPUState *cpu, bool halted);

/* Global function to retrieve current quantum timing for SAL/AAL */
extern void (*virtmcu_get_quantum_timing)(VirtmcuQuantumTiming *timing);

#endif
"""

    write_if_changed(hooks_h, hooks_h_content)

    cpu_exec_c = os.path.join(qemu, "accel", "tcg", "cpu-exec.c")

    # 2. Add include to cpu-exec.c
    marker0 = '#include "internal-common.h"'
    insertion0 = '\n#include "virtmcu/hooks.h"'
    patch_file(cpu_exec_c, marker0, insertion0, after=True)

    # 3. Patch hw/core/irq.c
    irq_c = os.path.join(qemu, "hw", "core", "irq.c")
    patch_file(irq_c, '#include "hw/core/irq.h"', '\n#include "virtmcu/hooks.h"', after=True)

    # Add the function pointer definitions separately for idempotency
    patch_file(
        irq_c,
        '#include "virtmcu/hooks.h"',
        "\nvoid (*virtmcu_tcg_quantum_hook)(CPUState *cpu) = NULL;\nvoid (*virtmcu_get_quantum_timing)(VirtmcuQuantumTiming *timing) = NULL;\nvoid (*virtmcu_irq_hook)(void *opaque, int n, int level) = NULL;\nvoid (*virtmcu_cpu_halt_hook)(CPUState *cpu, bool halted) = NULL;\n",
        after=True,
    )

    irq_marker = "void qemu_set_irq(qemu_irq irq, int level)\n{"
    irq_insertion = """
    if (virtmcu_irq_hook) {
        virtmcu_irq_hook(irq ? irq->opaque : NULL, irq ? irq->n : -1, level);
    }
"""
    patch_file(irq_c, irq_marker, irq_insertion, after=True)

    # 4. Add the hook invocation in cpu_exec_loop
    loop_marker = "while (!cpu_handle_exception(cpu, &ret)) {"
    loop_insertion = "\n        if (virtmcu_tcg_quantum_hook) { virtmcu_tcg_quantum_hook(cpu); }\n"
    patch_file(cpu_exec_c, loop_marker, loop_insertion, after=True)

    # 6. Patch cpu_handle_halt in cpu-exec.c
    halt_marker = "cpu->halted = 0;"
    halt_insertion = "\n        if (virtmcu_cpu_halt_hook) { virtmcu_cpu_halt_hook(cpu, false); }\n"
    patch_file(cpu_exec_c, halt_marker, halt_insertion, after=True)

    # 7. Inject BQL helper implementations into system/cpus.c
    # bql_locked() uses a file-static TLS variable in cpus.c; DSOs read a separate
    # copy and always see false. These wrappers live inside the main binary and
    # return the authoritative value.
    cpus_c = os.path.join(qemu, "system", "cpus.c")
    patch_file(
        cpus_c,
        "void bql_unlock(void)\n{\n    g_assert(bql_locked());\n    g_assert(!bql_unlock_blocked);\n    qemu_mutex_unlock(&bql);\n}",
        "\nbool virtmcu_is_bql_locked(void) { return bql_locked(); }\nvoid virtmcu_safe_bql_unlock(void) { if (bql_locked()) bql_unlock(); }\nvoid virtmcu_safe_bql_lock(void) { if (!bql_locked()) bql_lock(); }\n",
        after=True,
    )

    # 8. Inject BQL helper declarations into include/qemu/main-loop.h
    main_loop_h = os.path.join(qemu, "include", "qemu", "main-loop.h")
    patch_file(
        main_loop_h,
        "bool bql_locked(void);",
        "\nbool virtmcu_is_bql_locked(void);\nvoid virtmcu_safe_bql_unlock(void);\nvoid virtmcu_safe_bql_lock(void);\n",
        after=True,
    )

    # We also need to hook where halted is set to 1.
    # This is target-specific, but let's try to find a generic place or common targets.
    # In ARM:
    arm_op_helper = os.path.join(qemu, "target", "arm", "tcg", "op_helper.c")
    if os.path.exists(arm_op_helper):
        patch_file(arm_op_helper, '#include "qemu/osdep.h"', '\n#include "virtmcu/hooks.h"', after=True)
        patch_file(
            arm_op_helper,
            "cs->halted = 1;",
            "\n    if (virtmcu_cpu_halt_hook) { virtmcu_cpu_halt_hook(cs, true); }\n",
            after=False,
        )


if __name__ == "__main__":
    main()
