// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod can {

        pub enum CanFdFrameOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct CanFdFrame<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for CanFdFrame<'a> {
            type Inner = CanFdFrame<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> CanFdFrame<'a> {
            pub const VT_DELIVERY_VTIME_NS: ::flatbuffers::VOffsetT = 4;
            pub const VT_CAN_ID: ::flatbuffers::VOffsetT = 6;
            pub const VT_FLAGS: ::flatbuffers::VOffsetT = 8;
            pub const VT_DATA: ::flatbuffers::VOffsetT = 10;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                CanFdFrame { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args CanFdFrameArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<CanFdFrame<'bldr>> {
                let mut builder = CanFdFrameBuilder::new(_fbb);
                builder.add_delivery_vtime_ns(args.delivery_vtime_ns);
                if let Some(x) = args.data {
                    builder.add_data(x);
                }
                builder.add_flags(args.flags);
                builder.add_can_id(args.can_id);
                builder.finish()
            }

            #[inline]
            pub fn delivery_vtime_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(CanFdFrame::VT_DELIVERY_VTIME_NS, Some(0)).unwrap() }
            }
            #[inline]
            pub fn can_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(CanFdFrame::VT_CAN_ID, Some(0)).unwrap() }
            }
            #[inline]
            pub fn flags(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(CanFdFrame::VT_FLAGS, Some(0)).unwrap() }
            }
            #[inline]
            pub fn data(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        CanFdFrame::VT_DATA,
                        None,
                    )
                }
            }
        }

        impl ::flatbuffers::Verifiable for CanFdFrame<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("delivery_vtime_ns", Self::VT_DELIVERY_VTIME_NS, false)?
                    .visit_field::<u32>("can_id", Self::VT_CAN_ID, false)?
                    .visit_field::<u32>("flags", Self::VT_FLAGS, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "data",
                        Self::VT_DATA,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct CanFdFrameArgs<'a> {
            pub delivery_vtime_ns: u64,
            pub can_id: u32,
            pub flags: u32,
            pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        }
        impl Default for CanFdFrameArgs<'_> {
            #[inline]
            fn default() -> Self {
                CanFdFrameArgs { delivery_vtime_ns: 0, can_id: 0, flags: 0, data: None }
            }
        }

        pub struct CanFdFrameBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CanFdFrameBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_delivery_vtime_ns(&mut self, delivery_vtime_ns: u64) {
                self.fbb_.push_slot::<u64>(CanFdFrame::VT_DELIVERY_VTIME_NS, delivery_vtime_ns, 0);
            }
            #[inline]
            pub fn add_can_id(&mut self, can_id: u32) {
                self.fbb_.push_slot::<u32>(CanFdFrame::VT_CAN_ID, can_id, 0);
            }
            #[inline]
            pub fn add_flags(&mut self, flags: u32) {
                self.fbb_.push_slot::<u32>(CanFdFrame::VT_FLAGS, flags, 0);
            }
            #[inline]
            pub fn add_data(
                &mut self,
                data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_
                    .push_slot_always::<::flatbuffers::WIPOffset<_>>(CanFdFrame::VT_DATA, data);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> CanFdFrameBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                CanFdFrameBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<CanFdFrame<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for CanFdFrame<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("CanFdFrame");
                ds.field("delivery_vtime_ns", &self.delivery_vtime_ns());
                ds.field("can_id", &self.can_id());
                ds.field("flags", &self.flags());
                ds.field("data", &self.data());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `CanFdFrame`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_can_fd_frame_unchecked`.
        pub fn root_as_can_fd_frame(
            buf: &[u8],
        ) -> Result<CanFdFrame<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<CanFdFrame>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `CanFdFrame` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_can_fd_frame_unchecked`.
        pub fn size_prefixed_root_as_can_fd_frame(
            buf: &[u8],
        ) -> Result<CanFdFrame<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<CanFdFrame>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `CanFdFrame` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_can_fd_frame_unchecked`.
        pub fn root_as_can_fd_frame_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<CanFdFrame<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<CanFdFrame<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `CanFdFrame` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_can_fd_frame_unchecked`.
        pub fn size_prefixed_root_as_can_fd_frame_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<CanFdFrame<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<CanFdFrame<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a CanFdFrame and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `CanFdFrame`.
        pub unsafe fn root_as_can_fd_frame_unchecked(buf: &[u8]) -> CanFdFrame<'_> {
            unsafe { ::flatbuffers::root_unchecked::<CanFdFrame>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed CanFdFrame and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `CanFdFrame`.
        pub unsafe fn size_prefixed_root_as_can_fd_frame_unchecked(buf: &[u8]) -> CanFdFrame<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<CanFdFrame>(buf) }
        }
        #[inline]
        pub fn finish_can_fd_frame_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<CanFdFrame<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_can_fd_frame_buffer<
            'a,
            'b,
            A: ::flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<CanFdFrame<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod can
} // pub mod virtmcu
