// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod lin {

        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MIN_LIN_MESSAGE_TYPE: u8 = 0;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MAX_LIN_MESSAGE_TYPE: u8 = 2;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_LIN_MESSAGE_TYPE: [LinMessageType; 3] =
            [LinMessageType::Data, LinMessageType::Break, LinMessageType::Sync];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct LinMessageType(pub u8);
        #[allow(non_upper_case_globals)]
        impl LinMessageType {
            pub const Data: Self = Self(0);
            pub const Break: Self = Self(1);
            pub const Sync: Self = Self(2);

            pub const ENUM_MIN: u8 = 0;
            pub const ENUM_MAX: u8 = 2;
            pub const ENUM_VALUES: &'static [Self] = &[Self::Data, Self::Break, Self::Sync];
            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::Data => Some("Data"),
                    Self::Break => Some("Break"),
                    Self::Sync => Some("Sync"),
                    _ => None,
                }
            }
        }
        impl ::core::fmt::Debug for LinMessageType {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for LinMessageType {
            type Inner = Self;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for LinMessageType {
            type Output = LinMessageType;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for LinMessageType {
            type Scalar = u8;
            #[inline]
            fn to_little_endian(self) -> u8 {
                self.0.to_le()
            }
            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: u8) -> Self {
                let b = u8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for LinMessageType {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                u8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for LinMessageType {}
        pub enum LinFrameOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct LinFrame<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for LinFrame<'a> {
            type Inner = LinFrame<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> LinFrame<'a> {
            pub const VT_DELIVERY_VTIME_NS: ::flatbuffers::VOffsetT = 4;
            pub const VT_TYPE_: ::flatbuffers::VOffsetT = 6;
            pub const VT_DATA: ::flatbuffers::VOffsetT = 8;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                LinFrame { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args LinFrameArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<LinFrame<'bldr>> {
                let mut builder = LinFrameBuilder::new(_fbb);
                builder.add_delivery_vtime_ns(args.delivery_vtime_ns);
                if let Some(x) = args.data {
                    builder.add_data(x);
                }
                builder.add_type_(args.type_);
                builder.finish()
            }

            #[inline]
            pub fn delivery_vtime_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(LinFrame::VT_DELIVERY_VTIME_NS, Some(0)).unwrap() }
            }
            #[inline]
            pub fn type_(&self) -> LinMessageType {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<LinMessageType>(LinFrame::VT_TYPE_, Some(LinMessageType::Data))
                        .unwrap()
                }
            }
            #[inline]
            pub fn data(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        LinFrame::VT_DATA,
                        None,
                    )
                }
            }
        }

        impl ::flatbuffers::Verifiable for LinFrame<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("delivery_vtime_ns", Self::VT_DELIVERY_VTIME_NS, false)?
                    .visit_field::<LinMessageType>("type_", Self::VT_TYPE_, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "data",
                        Self::VT_DATA,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct LinFrameArgs<'a> {
            pub delivery_vtime_ns: u64,
            pub type_: LinMessageType,
            pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        }
        impl Default for LinFrameArgs<'_> {
            #[inline]
            fn default() -> Self {
                LinFrameArgs { delivery_vtime_ns: 0, type_: LinMessageType::Data, data: None }
            }
        }

        pub struct LinFrameBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LinFrameBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_delivery_vtime_ns(&mut self, delivery_vtime_ns: u64) {
                self.fbb_.push_slot::<u64>(LinFrame::VT_DELIVERY_VTIME_NS, delivery_vtime_ns, 0);
            }
            #[inline]
            pub fn add_type_(&mut self, type_: LinMessageType) {
                self.fbb_.push_slot::<LinMessageType>(
                    LinFrame::VT_TYPE_,
                    type_,
                    LinMessageType::Data,
                );
            }
            #[inline]
            pub fn add_data(
                &mut self,
                data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LinFrame::VT_DATA, data);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> LinFrameBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                LinFrameBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<LinFrame<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for LinFrame<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("LinFrame");
                ds.field("delivery_vtime_ns", &self.delivery_vtime_ns());
                ds.field("type_", &self.type_());
                ds.field("data", &self.data());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `LinFrame`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_lin_frame_unchecked`.
        pub fn root_as_lin_frame(
            buf: &[u8],
        ) -> Result<LinFrame<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<LinFrame>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `LinFrame` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_lin_frame_unchecked`.
        pub fn size_prefixed_root_as_lin_frame(
            buf: &[u8],
        ) -> Result<LinFrame<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<LinFrame>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `LinFrame` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_lin_frame_unchecked`.
        pub fn root_as_lin_frame_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<LinFrame<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<LinFrame<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `LinFrame` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_lin_frame_unchecked`.
        pub fn size_prefixed_root_as_lin_frame_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<LinFrame<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<LinFrame<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a LinFrame and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `LinFrame`.
        pub unsafe fn root_as_lin_frame_unchecked(buf: &[u8]) -> LinFrame<'_> {
            unsafe { ::flatbuffers::root_unchecked::<LinFrame>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed LinFrame and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `LinFrame`.
        pub unsafe fn size_prefixed_root_as_lin_frame_unchecked(buf: &[u8]) -> LinFrame<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<LinFrame>(buf) }
        }
        #[inline]
        pub fn finish_lin_frame_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<LinFrame<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_lin_frame_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<LinFrame<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod lin
} // pub mod virtmcu
