// automatically generated by the FlatBuffers compiler, do not modify
// @generated
#![allow(clippy::all)]
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod telemetry {

        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MIN_TRACE_EVENT_TYPE: i8 = 0;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MAX_TRACE_EVENT_TYPE: i8 = 2;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_TRACE_EVENT_TYPE: [TraceEventType; 3] =
            [TraceEventType::CPU_STATE, TraceEventType::IRQ, TraceEventType::PERIPHERAL];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct TraceEventType(pub i8);
        #[allow(non_upper_case_globals)]
        impl TraceEventType {
            pub const CPU_STATE: Self = Self(0);
            pub const IRQ: Self = Self(1);
            pub const PERIPHERAL: Self = Self(2);

            pub const ENUM_MIN: i8 = 0;
            pub const ENUM_MAX: i8 = 2;
            pub const ENUM_VALUES: &'static [Self] =
                &[Self::CPU_STATE, Self::IRQ, Self::PERIPHERAL];
            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::CPU_STATE => Some("CPU_STATE"),
                    Self::IRQ => Some("IRQ"),
                    Self::PERIPHERAL => Some("PERIPHERAL"),
                    _ => None,
                }
            }
        }
        impl ::core::fmt::Debug for TraceEventType {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for TraceEventType {
            type Inner = Self;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for TraceEventType {
            type Output = TraceEventType;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for TraceEventType {
            type Scalar = i8;
            #[inline]
            fn to_little_endian(self) -> i8 {
                self.0.to_le()
            }
            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: i8) -> Self {
                let b = i8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for TraceEventType {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                i8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for TraceEventType {}
        pub enum TraceEventOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct TraceEvent<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for TraceEvent<'a> {
            type Inner = TraceEvent<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> TraceEvent<'a> {
            pub const VT_TIMESTAMP_NS: ::flatbuffers::VOffsetT = 4;
            pub const VT_TYPE_: ::flatbuffers::VOffsetT = 6;
            pub const VT_ID: ::flatbuffers::VOffsetT = 8;
            pub const VT_VALUE: ::flatbuffers::VOffsetT = 10;
            pub const VT_DEVICE_NAME: ::flatbuffers::VOffsetT = 12;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                TraceEvent { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args TraceEventArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<TraceEvent<'bldr>> {
                let mut builder = TraceEventBuilder::new(_fbb);
                builder.add_timestamp_ns(args.timestamp_ns);
                if let Some(x) = args.device_name {
                    builder.add_device_name(x);
                }
                builder.add_value(args.value);
                builder.add_id(args.id);
                builder.add_type_(args.type_);
                builder.finish()
            }

            #[inline]
            pub fn timestamp_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(TraceEvent::VT_TIMESTAMP_NS, Some(0)).unwrap() }
            }
            #[inline]
            pub fn type_(&self) -> TraceEventType {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<TraceEventType>(
                            TraceEvent::VT_TYPE_,
                            Some(TraceEventType::CPU_STATE),
                        )
                        .unwrap()
                }
            }
            #[inline]
            pub fn id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(TraceEvent::VT_ID, Some(0)).unwrap() }
            }
            #[inline]
            pub fn value(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(TraceEvent::VT_VALUE, Some(0)).unwrap() }
            }
            #[inline]
            pub fn device_name(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                        TraceEvent::VT_DEVICE_NAME,
                        None,
                    )
                }
            }
        }

        impl ::flatbuffers::Verifiable for TraceEvent<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("timestamp_ns", Self::VT_TIMESTAMP_NS, false)?
                    .visit_field::<TraceEventType>("type_", Self::VT_TYPE_, false)?
                    .visit_field::<u32>("id", Self::VT_ID, false)?
                    .visit_field::<u32>("value", Self::VT_VALUE, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "device_name",
                        Self::VT_DEVICE_NAME,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct TraceEventArgs<'a> {
            pub timestamp_ns: u64,
            pub type_: TraceEventType,
            pub id: u32,
            pub value: u32,
            pub device_name: Option<::flatbuffers::WIPOffset<&'a str>>,
        }
        impl Default for TraceEventArgs<'_> {
            #[inline]
            fn default() -> Self {
                TraceEventArgs {
                    timestamp_ns: 0,
                    type_: TraceEventType::CPU_STATE,
                    id: 0,
                    value: 0,
                    device_name: None,
                }
            }
        }

        pub struct TraceEventBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TraceEventBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_timestamp_ns(&mut self, timestamp_ns: u64) {
                self.fbb_.push_slot::<u64>(TraceEvent::VT_TIMESTAMP_NS, timestamp_ns, 0);
            }
            #[inline]
            pub fn add_type_(&mut self, type_: TraceEventType) {
                self.fbb_.push_slot::<TraceEventType>(
                    TraceEvent::VT_TYPE_,
                    type_,
                    TraceEventType::CPU_STATE,
                );
            }
            #[inline]
            pub fn add_id(&mut self, id: u32) {
                self.fbb_.push_slot::<u32>(TraceEvent::VT_ID, id, 0);
            }
            #[inline]
            pub fn add_value(&mut self, value: u32) {
                self.fbb_.push_slot::<u32>(TraceEvent::VT_VALUE, value, 0);
            }
            #[inline]
            pub fn add_device_name(&mut self, device_name: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    TraceEvent::VT_DEVICE_NAME,
                    device_name,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> TraceEventBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                TraceEventBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<TraceEvent<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for TraceEvent<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("TraceEvent");
                ds.field("timestamp_ns", &self.timestamp_ns());
                ds.field("type_", &self.type_());
                ds.field("id", &self.id());
                ds.field("value", &self.value());
                ds.field("device_name", &self.device_name());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `TraceEvent`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_trace_event_unchecked`.
        pub fn root_as_trace_event(
            buf: &[u8],
        ) -> Result<TraceEvent<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<TraceEvent>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `TraceEvent` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_trace_event_unchecked`.
        pub fn size_prefixed_root_as_trace_event(
            buf: &[u8],
        ) -> Result<TraceEvent<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<TraceEvent>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `TraceEvent` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_trace_event_unchecked`.
        pub fn root_as_trace_event_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<TraceEvent<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<TraceEvent<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `TraceEvent` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_trace_event_unchecked`.
        pub fn size_prefixed_root_as_trace_event_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<TraceEvent<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<TraceEvent<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a TraceEvent and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `TraceEvent`.
        pub unsafe fn root_as_trace_event_unchecked(buf: &[u8]) -> TraceEvent<'_> {
            unsafe { ::flatbuffers::root_unchecked::<TraceEvent>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed TraceEvent and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `TraceEvent`.
        pub unsafe fn size_prefixed_root_as_trace_event_unchecked(buf: &[u8]) -> TraceEvent<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<TraceEvent>(buf) }
        }
        #[inline]
        pub fn finish_trace_event_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<TraceEvent<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_trace_event_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<TraceEvent<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod Telemetry
} // pub mod Virtmcu
