// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod wifi {

        pub enum WifiHeaderOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct WifiHeader<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for WifiHeader<'a> {
            type Inner = WifiHeader<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> WifiHeader<'a> {
            pub const VT_DELIVERY_VTIME_NS: ::flatbuffers::VOffsetT = 4;
            pub const VT_SIZE: ::flatbuffers::VOffsetT = 6;
            pub const VT_CHANNEL: ::flatbuffers::VOffsetT = 8;
            pub const VT_RSSI: ::flatbuffers::VOffsetT = 10;
            pub const VT_SNR: ::flatbuffers::VOffsetT = 12;
            pub const VT_FRAME_TYPE: ::flatbuffers::VOffsetT = 14;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                WifiHeader { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args WifiHeaderArgs,
            ) -> ::flatbuffers::WIPOffset<WifiHeader<'bldr>> {
                let mut builder = WifiHeaderBuilder::new(_fbb);
                builder.add_delivery_vtime_ns(args.delivery_vtime_ns);
                builder.add_size(args.size);
                builder.add_channel(args.channel);
                builder.add_frame_type(args.frame_type);
                builder.add_snr(args.snr);
                builder.add_rssi(args.rssi);
                builder.finish()
            }

            #[inline]
            pub fn delivery_vtime_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(WifiHeader::VT_DELIVERY_VTIME_NS, Some(0)).unwrap() }
            }
            #[inline]
            pub fn size(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(WifiHeader::VT_SIZE, Some(0)).unwrap() }
            }
            #[inline]
            pub fn channel(&self) -> u16 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u16>(WifiHeader::VT_CHANNEL, Some(0)).unwrap() }
            }
            #[inline]
            pub fn rssi(&self) -> i8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<i8>(WifiHeader::VT_RSSI, Some(0)).unwrap() }
            }
            #[inline]
            pub fn snr(&self) -> i8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<i8>(WifiHeader::VT_SNR, Some(0)).unwrap() }
            }
            #[inline]
            pub fn frame_type(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u8>(WifiHeader::VT_FRAME_TYPE, Some(0)).unwrap() }
            }
        }

        impl ::flatbuffers::Verifiable for WifiHeader<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("delivery_vtime_ns", Self::VT_DELIVERY_VTIME_NS, false)?
                    .visit_field::<u32>("size", Self::VT_SIZE, false)?
                    .visit_field::<u16>("channel", Self::VT_CHANNEL, false)?
                    .visit_field::<i8>("rssi", Self::VT_RSSI, false)?
                    .visit_field::<i8>("snr", Self::VT_SNR, false)?
                    .visit_field::<u8>("frame_type", Self::VT_FRAME_TYPE, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct WifiHeaderArgs {
            pub delivery_vtime_ns: u64,
            pub size: u32,
            pub channel: u16,
            pub rssi: i8,
            pub snr: i8,
            pub frame_type: u8,
        }
        impl<'a> Default for WifiHeaderArgs {
            #[inline]
            fn default() -> Self {
                WifiHeaderArgs {
                    delivery_vtime_ns: 0,
                    size: 0,
                    channel: 0,
                    rssi: 0,
                    snr: 0,
                    frame_type: 0,
                }
            }
        }

        pub struct WifiHeaderBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WifiHeaderBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_delivery_vtime_ns(&mut self, delivery_vtime_ns: u64) {
                self.fbb_.push_slot::<u64>(WifiHeader::VT_DELIVERY_VTIME_NS, delivery_vtime_ns, 0);
            }
            #[inline]
            pub fn add_size(&mut self, size: u32) {
                self.fbb_.push_slot::<u32>(WifiHeader::VT_SIZE, size, 0);
            }
            #[inline]
            pub fn add_channel(&mut self, channel: u16) {
                self.fbb_.push_slot::<u16>(WifiHeader::VT_CHANNEL, channel, 0);
            }
            #[inline]
            pub fn add_rssi(&mut self, rssi: i8) {
                self.fbb_.push_slot::<i8>(WifiHeader::VT_RSSI, rssi, 0);
            }
            #[inline]
            pub fn add_snr(&mut self, snr: i8) {
                self.fbb_.push_slot::<i8>(WifiHeader::VT_SNR, snr, 0);
            }
            #[inline]
            pub fn add_frame_type(&mut self, frame_type: u8) {
                self.fbb_.push_slot::<u8>(WifiHeader::VT_FRAME_TYPE, frame_type, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> WifiHeaderBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                WifiHeaderBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<WifiHeader<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for WifiHeader<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("WifiHeader");
                ds.field("delivery_vtime_ns", &self.delivery_vtime_ns());
                ds.field("size", &self.size());
                ds.field("channel", &self.channel());
                ds.field("rssi", &self.rssi());
                ds.field("snr", &self.snr());
                ds.field("frame_type", &self.frame_type());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `WifiHeader`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_wifi_header_unchecked`.
        pub fn root_as_wifi_header(
            buf: &[u8],
        ) -> Result<WifiHeader<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<WifiHeader>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `WifiHeader` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_wifi_header_unchecked`.
        pub fn size_prefixed_root_as_wifi_header(
            buf: &[u8],
        ) -> Result<WifiHeader<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<WifiHeader>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `WifiHeader` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_wifi_header_unchecked`.
        pub fn root_as_wifi_header_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<WifiHeader<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<WifiHeader<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `WifiHeader` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_wifi_header_unchecked`.
        pub fn size_prefixed_root_as_wifi_header_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<WifiHeader<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<WifiHeader<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a WifiHeader and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `WifiHeader`.
        pub unsafe fn root_as_wifi_header_unchecked(buf: &[u8]) -> WifiHeader<'_> {
            unsafe { ::flatbuffers::root_unchecked::<WifiHeader>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed WifiHeader and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `WifiHeader`.
        pub unsafe fn size_prefixed_root_as_wifi_header_unchecked(buf: &[u8]) -> WifiHeader<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<WifiHeader>(buf) }
        }
        #[inline]
        pub fn finish_wifi_header_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<WifiHeader<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_wifi_header_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<WifiHeader<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod wifi
} // pub mod virtmcu
