# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rf


import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()

class RfHeader:
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RfHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRfHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RfHeader
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RfHeader
    def DeliveryVtimeNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RfHeader
    def SequenceNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RfHeader
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RfHeader
    def Rssi(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # RfHeader
    def Lqi(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 255

def RfHeaderStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    RfHeaderStart(builder)

def RfHeaderAddDeliveryVtimeNs(builder: flatbuffers.Builder, deliveryVtimeNs: int):
    builder.PrependUint64Slot(0, deliveryVtimeNs, 0)

def AddDeliveryVtimeNs(builder: flatbuffers.Builder, deliveryVtimeNs: int):
    RfHeaderAddDeliveryVtimeNs(builder, deliveryVtimeNs)

def RfHeaderAddSequenceNumber(builder: flatbuffers.Builder, sequenceNumber: int):
    builder.PrependUint64Slot(1, sequenceNumber, 0)

def AddSequenceNumber(builder: flatbuffers.Builder, sequenceNumber: int):
    RfHeaderAddSequenceNumber(builder, sequenceNumber)

def RfHeaderAddSize(builder: flatbuffers.Builder, size: int):
    builder.PrependUint32Slot(2, size, 0)

def AddSize(builder: flatbuffers.Builder, size: int):
    RfHeaderAddSize(builder, size)

def RfHeaderAddRssi(builder: flatbuffers.Builder, rssi: int):
    builder.PrependInt8Slot(3, rssi, 0)

def AddRssi(builder: flatbuffers.Builder, rssi: int):
    RfHeaderAddRssi(builder, rssi)

def RfHeaderAddLqi(builder: flatbuffers.Builder, lqi: int):
    builder.PrependUint8Slot(4, lqi, 255)

def AddLqi(builder: flatbuffers.Builder, lqi: int):
    RfHeaderAddLqi(builder, lqi)

def RfHeaderEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RfHeaderEnd(builder)
