# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core


import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()

class ClockReadyResp:
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 24

    # ClockReadyResp
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClockReadyResp
    def CurrentVtimeNs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ClockReadyResp
    def NFrames(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ClockReadyResp
    def ErrorCode(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # ClockReadyResp
    def QuantumNumber(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateClockReadyResp(builder, currentVtimeNs, nFrames, errorCode, quantumNumber):
    builder.Prep(8, 24)
    builder.PrependUint64(quantumNumber)
    builder.PrependUint32(errorCode)
    builder.PrependUint32(nFrames)
    builder.PrependUint64(currentVtimeNs)
    return builder.Offset()
