# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core


import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()

class ClockAdvanceReq:
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 24

    # ClockAdvanceReq
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClockAdvanceReq
    def DeltaNs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ClockAdvanceReq
    def MujocoTimeNs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ClockAdvanceReq
    def QuantumNumber(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateClockAdvanceReq(builder, deltaNs, mujocoTimeNs, quantumNumber):
    builder.Prep(8, 24)
    builder.PrependUint64(quantumNumber)
    builder.PrependUint64(mujocoTimeNs)
    builder.PrependUint64(deltaNs)
    return builder.Offset()
