from __future__ import annotations

import flatbuffers

type uoffset = flatbuffers.number_types.UOffsetTFlags.py_type

class ClockAdvanceReq:
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def DeltaNs(self) -> int: ...
  def MujocoTimeNs(self) -> int: ...
  def QuantumNumber(self) -> int: ...

def CreateClockAdvanceReq(builder: flatbuffers.Builder, deltaNs: int, mujocoTimeNs: int, quantumNumber: int) -> uoffset: ...

