from __future__ import annotations

import flatbuffers

type uoffset = flatbuffers.number_types.UOffsetTFlags.py_type

class ClockReadyResp:
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def CurrentVtimeNs(self) -> int: ...
  def NFrames(self) -> int: ...
  def ErrorCode(self) -> int: ...
  def QuantumNumber(self) -> int: ...

def CreateClockReadyResp(builder: flatbuffers.Builder, currentVtimeNs: int, nFrames: int, errorCode: int, quantumNumber: int) -> uoffset: ...

