# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CoordDoneReq(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CoordDoneReq()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCoordDoneReq(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CoordDoneReq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CoordDoneReq
    def Quantum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CoordDoneReq
    def VtimeLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CoordDoneReq
    def Messages(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from virtmcu.core.CoordMessage import CoordMessage
            obj = CoordMessage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CoordDoneReq
    def MessagesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CoordDoneReq
    def MessagesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def CoordDoneReqStart(builder):
    builder.StartObject(3)

def Start(builder):
    CoordDoneReqStart(builder)

def CoordDoneReqAddQuantum(builder, quantum):
    builder.PrependUint64Slot(0, quantum, 0)

def AddQuantum(builder, quantum):
    CoordDoneReqAddQuantum(builder, quantum)

def CoordDoneReqAddVtimeLimit(builder, vtimeLimit):
    builder.PrependUint64Slot(1, vtimeLimit, 0)

def AddVtimeLimit(builder, vtimeLimit):
    CoordDoneReqAddVtimeLimit(builder, vtimeLimit)

def CoordDoneReqAddMessages(builder, messages):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(messages), 0)

def AddMessages(builder, messages):
    CoordDoneReqAddMessages(builder, messages)

def CoordDoneReqStartMessagesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMessagesVector(builder, numElems):
    return CoordDoneReqStartMessagesVector(builder, numElems)

def CoordDoneReqEnd(builder):
    return builder.EndObject()

def End(builder):
    return CoordDoneReqEnd(builder)
