# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MmioReq(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 32

    # MmioReq
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MmioReq
    def Type_(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MmioReq
    def Size(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # MmioReq
    def Reserved1(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # MmioReq
    def Reserved2(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # MmioReq
    def VtimeNs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # MmioReq
    def Addr(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # MmioReq
    def Data(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))

def CreateMmioReq(builder, type_, size, reserved1, reserved2, vtimeNs, addr, data):
    builder.Prep(8, 32)
    builder.PrependUint64(data)
    builder.PrependUint64(addr)
    builder.PrependUint64(vtimeNs)
    builder.PrependUint32(reserved2)
    builder.PrependUint16(reserved1)
    builder.PrependUint8(size)
    builder.PrependUint8(type_)
    return builder.Offset()
