from __future__ import annotations

import flatbuffers

type uoffset = flatbuffers.number_types.UOffsetTFlags.py_type

class MmioReq:
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Type_(self) -> int: ...
  def Size(self) -> int: ...
  def Reserved1(self) -> int: ...
  def Reserved2(self) -> int: ...
  def VtimeNs(self) -> int: ...
  def Addr(self) -> int: ...
  def Data(self) -> int: ...

def CreateMmioReq(builder: flatbuffers.Builder, type_: int, size: int, reserved1: int, reserved2: int, vtimeNs: int, addr: int, data: int) -> uoffset: ...

