# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

class Protocol(object):
    Ethernet = 0
    Uart = 1
    Spi = 2
    CanFd = 3
    FlexRay = 4
    Lin = 5
    Rf802154 = 6
    RfHci = 7
    Control = 8
