from __future__ import annotations

import flatbuffers

type uoffset = flatbuffers.number_types.UOffsetTFlags.py_type

class SyscMsg:
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Type_(self) -> int: ...
  def IrqNum(self) -> int: ...
  def Data(self) -> int: ...

def CreateSyscMsg(builder: flatbuffers.Builder, type_: int, irqNum: int, data: int) -> uoffset: ...

