# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SyscMsg(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # SyscMsg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SyscMsg
    def Type_(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # SyscMsg
    def IrqNum(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # SyscMsg
    def Data(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateSyscMsg(builder, type_, irqNum, data):
    builder.Prep(8, 16)
    builder.PrependUint64(data)
    builder.PrependUint32(irqNum)
    builder.PrependUint32(type_)
    return builder.Offset()
