# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core


import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()

class VirtmcuHandshake:
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 8

    # VirtmcuHandshake
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VirtmcuHandshake
    def Magic(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # VirtmcuHandshake
    def Version(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateVirtmcuHandshake(builder, magic, version):
    builder.Prep(4, 8)
    builder.PrependUint32(version)
    builder.PrependUint32(magic)
    return builder.Offset()
