from __future__ import annotations

import flatbuffers

type uoffset = flatbuffers.number_types.UOffsetTFlags.py_type

class ZenohFrameHeader:
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def DeliveryVtimeNs(self) -> int: ...
  def SequenceNumber(self) -> int: ...
  def Size(self) -> int: ...

def CreateZenohFrameHeader(builder: flatbuffers.Builder, deliveryVtimeNs: int, sequenceNumber: int, size: int) -> uoffset: ...

