# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ZenohFrameHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # ZenohFrameHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ZenohFrameHeader
    def DeliveryVtimeNs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ZenohFrameHeader
    def SequenceNumber(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ZenohFrameHeader
    def Size(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateZenohFrameHeader(builder, deliveryVtimeNs, sequenceNumber, size):
    builder.Prep(8, 24)
    builder.Pad(4)
    builder.PrependUint32(size)
    builder.PrependUint64(sequenceNumber)
    builder.PrependUint64(deliveryVtimeNs)
    return builder.Offset()
