from __future__ import annotations

import flatbuffers

type uoffset = flatbuffers.number_types.UOffsetTFlags.py_type

class ZenohSPIHeader:
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def DeliveryVtimeNs(self) -> int: ...
  def SequenceNumber(self) -> int: ...
  def Size(self) -> int: ...
  def Cs(self) -> bool: ...
  def CsIndex(self) -> int: ...
  def Padding(self) -> int: ...

def CreateZenohSpiheader(builder: flatbuffers.Builder, deliveryVtimeNs: int, sequenceNumber: int, size: int, cs: bool, csIndex: int, padding: int) -> uoffset: ...

