// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod core {

        // struct VirtmcuHandshake, aligned to 4
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct VirtmcuHandshake(pub [u8; 8]);
        impl Default for VirtmcuHandshake {
            fn default() -> Self {
                Self([0; 8])
            }
        }
        impl ::core::fmt::Debug for VirtmcuHandshake {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("VirtmcuHandshake")
                    .field("magic", &self.magic())
                    .field("version", &self.version())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for VirtmcuHandshake {}
        impl<'a> ::flatbuffers::Follow<'a> for VirtmcuHandshake {
            type Inner = &'a VirtmcuHandshake;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a VirtmcuHandshake>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a VirtmcuHandshake {
            type Inner = &'a VirtmcuHandshake;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<VirtmcuHandshake>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for VirtmcuHandshake {
            type Output = VirtmcuHandshake;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        core::ptr::from_ref::<VirtmcuHandshake>(self) as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(4)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for VirtmcuHandshake {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> VirtmcuHandshake {
            #[allow(clippy::too_many_arguments)]
            pub fn new(magic: u32, version: u32) -> Self {
                let mut s = Self([0; 8]);
                s.set_magic(magic);
                s.set_version(version);
                s
            }

            pub fn magic(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_magic(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn version(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_version(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct MmioReq, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct MmioReq(pub [u8; 32]);
        impl Default for MmioReq {
            fn default() -> Self {
                Self([0; 32])
            }
        }
        impl ::core::fmt::Debug for MmioReq {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("MmioReq")
                    .field("type_", &self.type_())
                    .field("size", &self.size())
                    .field("reserved1", &self.reserved1())
                    .field("reserved2", &self.reserved2())
                    .field("vtime_ns", &self.vtime_ns())
                    .field("addr", &self.addr())
                    .field("data", &self.data())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for MmioReq {}
        impl<'a> ::flatbuffers::Follow<'a> for MmioReq {
            type Inner = &'a MmioReq;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a MmioReq>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a MmioReq {
            type Inner = &'a MmioReq;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<MmioReq>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for MmioReq {
            type Output = MmioReq;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        core::ptr::from_ref::<MmioReq>(self) as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for MmioReq {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> MmioReq {
            #[allow(clippy::too_many_arguments)]
            pub fn new(
                type_: u8,
                size: u8,
                reserved1: u16,
                reserved2: u32,
                vtime_ns: u64,
                addr: u64,
                data: u64,
            ) -> Self {
                let mut s = Self([0; 32]);
                s.set_type_(type_);
                s.set_size(size);
                s.set_reserved1(reserved1);
                s.set_reserved2(reserved2);
                s.set_vtime_ns(vtime_ns);
                s.set_addr(addr);
                s.set_data(data);
                s
            }

            pub fn type_(&self) -> u8 {
                let mut mem =
                    ::core::mem::MaybeUninit::<<u8 as ::flatbuffers::EndianScalar>::Scalar>::uninit(
                    );
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_type_(&mut self, x: u8) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn size(&self) -> u8 {
                let mut mem =
                    ::core::mem::MaybeUninit::<<u8 as ::flatbuffers::EndianScalar>::Scalar>::uninit(
                    );
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[1..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_size(&mut self, x: u8) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[1..].as_mut_ptr(),
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn reserved1(&self) -> u16 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u16 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[2..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_reserved1(&mut self, x: u16) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[2..].as_mut_ptr(),
                        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn reserved2(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_reserved2(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn vtime_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_vtime_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn addr(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[16..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_addr(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[16..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn data(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[24..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_data(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[24..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct SyscMsg, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct SyscMsg(pub [u8; 16]);
        impl Default for SyscMsg {
            fn default() -> Self {
                Self([0; 16])
            }
        }
        impl ::core::fmt::Debug for SyscMsg {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("SyscMsg")
                    .field("type_", &self.type_())
                    .field("irq_num", &self.irq_num())
                    .field("data", &self.data())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for SyscMsg {}
        impl<'a> ::flatbuffers::Follow<'a> for SyscMsg {
            type Inner = &'a SyscMsg;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a SyscMsg>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a SyscMsg {
            type Inner = &'a SyscMsg;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<SyscMsg>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for SyscMsg {
            type Output = SyscMsg;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        core::ptr::from_ref::<SyscMsg>(self) as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for SyscMsg {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> SyscMsg {
            #[allow(clippy::too_many_arguments)]
            pub fn new(type_: u32, irq_num: u32, data: u64) -> Self {
                let mut s = Self([0; 16]);
                s.set_type_(type_);
                s.set_irq_num(irq_num);
                s.set_data(data);
                s
            }

            pub fn type_(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_type_(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn irq_num(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_irq_num(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn data(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_data(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct ClockAdvanceReq, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct ClockAdvanceReq(pub [u8; 24]);
        impl Default for ClockAdvanceReq {
            fn default() -> Self {
                Self([0; 24])
            }
        }
        impl ::core::fmt::Debug for ClockAdvanceReq {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("ClockAdvanceReq")
                    .field("delta_ns", &self.delta_ns())
                    .field("mujoco_time_ns", &self.mujoco_time_ns())
                    .field("quantum_number", &self.quantum_number())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for ClockAdvanceReq {}
        impl<'a> ::flatbuffers::Follow<'a> for ClockAdvanceReq {
            type Inner = &'a ClockAdvanceReq;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a ClockAdvanceReq>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a ClockAdvanceReq {
            type Inner = &'a ClockAdvanceReq;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<ClockAdvanceReq>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for ClockAdvanceReq {
            type Output = ClockAdvanceReq;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        core::ptr::from_ref::<ClockAdvanceReq>(self) as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for ClockAdvanceReq {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> ClockAdvanceReq {
            #[allow(clippy::too_many_arguments)]
            pub fn new(delta_ns: u64, mujoco_time_ns: u64, quantum_number: u64) -> Self {
                let mut s = Self([0; 24]);
                s.set_delta_ns(delta_ns);
                s.set_mujoco_time_ns(mujoco_time_ns);
                s.set_quantum_number(quantum_number);
                s
            }

            pub fn delta_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_delta_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn mujoco_time_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_mujoco_time_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn quantum_number(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[16..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_quantum_number(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[16..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct ClockReadyResp, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct ClockReadyResp(pub [u8; 24]);
        impl Default for ClockReadyResp {
            fn default() -> Self {
                Self([0; 24])
            }
        }
        impl ::core::fmt::Debug for ClockReadyResp {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("ClockReadyResp")
                    .field("current_vtime_ns", &self.current_vtime_ns())
                    .field("n_frames", &self.n_frames())
                    .field("error_code", &self.error_code())
                    .field("quantum_number", &self.quantum_number())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for ClockReadyResp {}
        impl<'a> ::flatbuffers::Follow<'a> for ClockReadyResp {
            type Inner = &'a ClockReadyResp;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a ClockReadyResp>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a ClockReadyResp {
            type Inner = &'a ClockReadyResp;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<ClockReadyResp>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for ClockReadyResp {
            type Output = ClockReadyResp;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        core::ptr::from_ref::<ClockReadyResp>(self) as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for ClockReadyResp {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> ClockReadyResp {
            #[allow(clippy::too_many_arguments)]
            pub fn new(
                current_vtime_ns: u64,
                n_frames: u32,
                error_code: u32,
                quantum_number: u64,
            ) -> Self {
                let mut s = Self([0; 24]);
                s.set_current_vtime_ns(current_vtime_ns);
                s.set_n_frames(n_frames);
                s.set_error_code(error_code);
                s.set_quantum_number(quantum_number);
                s
            }

            pub fn current_vtime_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_current_vtime_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn n_frames(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_n_frames(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn error_code(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[12..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_error_code(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[12..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn quantum_number(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[16..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_quantum_number(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[16..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct ZenohFrameHeader, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct ZenohFrameHeader(pub [u8; 24]);
        impl Default for ZenohFrameHeader {
            fn default() -> Self {
                Self([0; 24])
            }
        }
        impl ::core::fmt::Debug for ZenohFrameHeader {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("ZenohFrameHeader")
                    .field("delivery_vtime_ns", &self.delivery_vtime_ns())
                    .field("sequence_number", &self.sequence_number())
                    .field("size", &self.size())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for ZenohFrameHeader {}
        impl<'a> ::flatbuffers::Follow<'a> for ZenohFrameHeader {
            type Inner = &'a ZenohFrameHeader;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a ZenohFrameHeader>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a ZenohFrameHeader {
            type Inner = &'a ZenohFrameHeader;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<ZenohFrameHeader>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for ZenohFrameHeader {
            type Output = ZenohFrameHeader;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        core::ptr::from_ref::<ZenohFrameHeader>(self) as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for ZenohFrameHeader {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> ZenohFrameHeader {
            #[allow(clippy::too_many_arguments)]
            pub fn new(delivery_vtime_ns: u64, sequence_number: u64, size: u32) -> Self {
                let mut s = Self([0; 24]);
                s.set_delivery_vtime_ns(delivery_vtime_ns);
                s.set_sequence_number(sequence_number);
                s.set_size(size);
                s
            }

            pub fn delivery_vtime_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_delivery_vtime_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn sequence_number(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_sequence_number(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn size(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[16..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_size(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[16..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct ZenohSPIHeader, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct ZenohSPIHeader(pub [u8; 24]);
        impl Default for ZenohSPIHeader {
            fn default() -> Self {
                Self([0; 24])
            }
        }
        impl ::core::fmt::Debug for ZenohSPIHeader {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("ZenohSPIHeader")
                    .field("delivery_vtime_ns", &self.delivery_vtime_ns())
                    .field("sequence_number", &self.sequence_number())
                    .field("size", &self.size())
                    .field("cs", &self.cs())
                    .field("cs_index", &self.cs_index())
                    .field("padding", &self.padding())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for ZenohSPIHeader {}
        impl<'a> ::flatbuffers::Follow<'a> for ZenohSPIHeader {
            type Inner = &'a ZenohSPIHeader;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a ZenohSPIHeader>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a ZenohSPIHeader {
            type Inner = &'a ZenohSPIHeader;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<ZenohSPIHeader>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for ZenohSPIHeader {
            type Output = ZenohSPIHeader;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        core::ptr::from_ref::<ZenohSPIHeader>(self) as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for ZenohSPIHeader {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> ZenohSPIHeader {
            #[allow(clippy::too_many_arguments)]
            pub fn new(
                delivery_vtime_ns: u64,
                sequence_number: u64,
                size: u32,
                cs: bool,
                cs_index: u8,
                padding: u16,
            ) -> Self {
                let mut s = Self([0; 24]);
                s.set_delivery_vtime_ns(delivery_vtime_ns);
                s.set_sequence_number(sequence_number);
                s.set_size(size);
                s.set_cs(cs);
                s.set_cs_index(cs_index);
                s.set_padding(padding);
                s
            }

            pub fn delivery_vtime_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_delivery_vtime_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn sequence_number(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_sequence_number(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn size(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[16..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_size(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[16..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn cs(&self) -> bool {
                let mut mem = ::core::mem::MaybeUninit::<
                    <bool as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[20..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<bool as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_cs(&mut self, x: bool) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[20..].as_mut_ptr(),
                        ::core::mem::size_of::<<bool as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn cs_index(&self) -> u8 {
                let mut mem =
                    ::core::mem::MaybeUninit::<<u8 as ::flatbuffers::EndianScalar>::Scalar>::uninit(
                    );
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[21..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_cs_index(&mut self, x: u8) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[21..].as_mut_ptr(),
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn padding(&self) -> u16 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u16 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[22..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_padding(&mut self, x: u16) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        core::ptr::from_ref(&x_le) as *const u8,
                        self.0[22..].as_mut_ptr(),
                        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }
    } // pub mod core
} // pub mod virtmcu
