// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod flexray {

        pub enum FlexRayFrameOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct FlexRayFrame<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for FlexRayFrame<'a> {
            type Inner = FlexRayFrame<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> FlexRayFrame<'a> {
            pub const VT_DELIVERY_VTIME_NS: ::flatbuffers::VOffsetT = 4;
            pub const VT_FRAME_ID: ::flatbuffers::VOffsetT = 6;
            pub const VT_CYCLE_COUNT: ::flatbuffers::VOffsetT = 8;
            pub const VT_CHANNEL: ::flatbuffers::VOffsetT = 10;
            pub const VT_FLAGS: ::flatbuffers::VOffsetT = 12;
            pub const VT_DATA: ::flatbuffers::VOffsetT = 14;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                FlexRayFrame { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args FlexRayFrameArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<FlexRayFrame<'bldr>> {
                let mut builder = FlexRayFrameBuilder::new(_fbb);
                builder.add_delivery_vtime_ns(args.delivery_vtime_ns);
                if let Some(x) = args.data {
                    builder.add_data(x);
                }
                builder.add_flags(args.flags);
                builder.add_frame_id(args.frame_id);
                builder.add_channel(args.channel);
                builder.add_cycle_count(args.cycle_count);
                builder.finish()
            }

            #[inline]
            pub fn delivery_vtime_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<u64>(FlexRayFrame::VT_DELIVERY_VTIME_NS, Some(0)).unwrap()
                }
            }
            #[inline]
            pub fn frame_id(&self) -> u16 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u16>(FlexRayFrame::VT_FRAME_ID, Some(0)).unwrap() }
            }
            #[inline]
            pub fn cycle_count(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u8>(FlexRayFrame::VT_CYCLE_COUNT, Some(0)).unwrap() }
            }
            #[inline]
            pub fn channel(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u8>(FlexRayFrame::VT_CHANNEL, Some(0)).unwrap() }
            }
            #[inline]
            pub fn flags(&self) -> u16 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u16>(FlexRayFrame::VT_FLAGS, Some(0)).unwrap() }
            }
            #[inline]
            pub fn data(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        FlexRayFrame::VT_DATA,
                        None,
                    )
                }
            }
        }

        impl ::flatbuffers::Verifiable for FlexRayFrame<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("delivery_vtime_ns", Self::VT_DELIVERY_VTIME_NS, false)?
                    .visit_field::<u16>("frame_id", Self::VT_FRAME_ID, false)?
                    .visit_field::<u8>("cycle_count", Self::VT_CYCLE_COUNT, false)?
                    .visit_field::<u8>("channel", Self::VT_CHANNEL, false)?
                    .visit_field::<u16>("flags", Self::VT_FLAGS, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "data",
                        Self::VT_DATA,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct FlexRayFrameArgs<'a> {
            pub delivery_vtime_ns: u64,
            pub frame_id: u16,
            pub cycle_count: u8,
            pub channel: u8,
            pub flags: u16,
            pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        }
        impl Default for FlexRayFrameArgs<'_> {
            #[inline]
            fn default() -> Self {
                FlexRayFrameArgs {
                    delivery_vtime_ns: 0,
                    frame_id: 0,
                    cycle_count: 0,
                    channel: 0,
                    flags: 0,
                    data: None,
                }
            }
        }

        pub struct FlexRayFrameBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FlexRayFrameBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_delivery_vtime_ns(&mut self, delivery_vtime_ns: u64) {
                self.fbb_.push_slot::<u64>(
                    FlexRayFrame::VT_DELIVERY_VTIME_NS,
                    delivery_vtime_ns,
                    0,
                );
            }
            #[inline]
            pub fn add_frame_id(&mut self, frame_id: u16) {
                self.fbb_.push_slot::<u16>(FlexRayFrame::VT_FRAME_ID, frame_id, 0);
            }
            #[inline]
            pub fn add_cycle_count(&mut self, cycle_count: u8) {
                self.fbb_.push_slot::<u8>(FlexRayFrame::VT_CYCLE_COUNT, cycle_count, 0);
            }
            #[inline]
            pub fn add_channel(&mut self, channel: u8) {
                self.fbb_.push_slot::<u8>(FlexRayFrame::VT_CHANNEL, channel, 0);
            }
            #[inline]
            pub fn add_flags(&mut self, flags: u16) {
                self.fbb_.push_slot::<u16>(FlexRayFrame::VT_FLAGS, flags, 0);
            }
            #[inline]
            pub fn add_data(
                &mut self,
                data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_
                    .push_slot_always::<::flatbuffers::WIPOffset<_>>(FlexRayFrame::VT_DATA, data);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> FlexRayFrameBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                FlexRayFrameBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<FlexRayFrame<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for FlexRayFrame<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("FlexRayFrame");
                ds.field("delivery_vtime_ns", &self.delivery_vtime_ns());
                ds.field("frame_id", &self.frame_id());
                ds.field("cycle_count", &self.cycle_count());
                ds.field("channel", &self.channel());
                ds.field("flags", &self.flags());
                ds.field("data", &self.data());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `FlexRayFrame`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_flex_ray_frame_unchecked`.
        pub fn root_as_flex_ray_frame(
            buf: &[u8],
        ) -> Result<FlexRayFrame<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<FlexRayFrame>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `FlexRayFrame` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_flex_ray_frame_unchecked`.
        pub fn size_prefixed_root_as_flex_ray_frame(
            buf: &[u8],
        ) -> Result<FlexRayFrame<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<FlexRayFrame>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `FlexRayFrame` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_flex_ray_frame_unchecked`.
        pub fn root_as_flex_ray_frame_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<FlexRayFrame<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<FlexRayFrame<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `FlexRayFrame` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_flex_ray_frame_unchecked`.
        pub fn size_prefixed_root_as_flex_ray_frame_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<FlexRayFrame<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<FlexRayFrame<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a FlexRayFrame and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `FlexRayFrame`.
        pub unsafe fn root_as_flex_ray_frame_unchecked(buf: &[u8]) -> FlexRayFrame<'_> {
            unsafe { ::flatbuffers::root_unchecked::<FlexRayFrame>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed FlexRayFrame and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `FlexRayFrame`.
        pub unsafe fn size_prefixed_root_as_flex_ray_frame_unchecked(
            buf: &[u8],
        ) -> FlexRayFrame<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<FlexRayFrame>(buf) }
        }
        #[inline]
        pub fn finish_flex_ray_frame_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<FlexRayFrame<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_flex_ray_frame_buffer<
            'a,
            'b,
            A: ::flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<FlexRayFrame<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod flexray
} // pub mod virtmcu
