# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flexray

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FlexRayFrame:
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlexRayFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlexRayFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FlexRayFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlexRayFrame
    def DeliveryVtimeNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FlexRayFrame
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FlexRayFrame
    def CycleCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FlexRayFrame
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FlexRayFrame
    def Flags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FlexRayFrame
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1)
            )
        return 0

    # FlexRayFrame
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FlexRayFrame
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlexRayFrame
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0


def FlexRayFrameStart(builder):
    builder.StartObject(6)


def Start(builder):
    FlexRayFrameStart(builder)


def FlexRayFrameAddDeliveryVtimeNs(builder, deliveryVtimeNs):
    builder.PrependUint64Slot(0, deliveryVtimeNs, 0)


def AddDeliveryVtimeNs(builder, deliveryVtimeNs):
    FlexRayFrameAddDeliveryVtimeNs(builder, deliveryVtimeNs)


def FlexRayFrameAddFrameId(builder, frameId):
    builder.PrependUint16Slot(1, frameId, 0)


def AddFrameId(builder, frameId):
    FlexRayFrameAddFrameId(builder, frameId)


def FlexRayFrameAddCycleCount(builder, cycleCount):
    builder.PrependUint8Slot(2, cycleCount, 0)


def AddCycleCount(builder, cycleCount):
    FlexRayFrameAddCycleCount(builder, cycleCount)


def FlexRayFrameAddChannel(builder, channel):
    builder.PrependUint8Slot(3, channel, 0)


def AddChannel(builder, channel):
    FlexRayFrameAddChannel(builder, channel)


def FlexRayFrameAddFlags(builder, flags):
    builder.PrependUint16Slot(4, flags, 0)


def AddFlags(builder, flags):
    FlexRayFrameAddFlags(builder, flags)


def FlexRayFrameAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)


def AddData(builder, data):
    FlexRayFrameAddData(builder, data)


def FlexRayFrameStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)


def StartDataVector(builder, numElems):
    return FlexRayFrameStartDataVector(builder, numElems)


def FlexRayFrameEnd(builder):
    return builder.EndObject()


def End(builder):
    return FlexRayFrameEnd(builder)
