from __future__ import annotations

import flatbuffers
import numpy as np

type uoffset = flatbuffers.number_types.UOffsetTFlags.py_type

class FlexRayFrame:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FlexRayFrame: ...
  @classmethod
  def GetRootAsFlexRayFrame(cls, buf: bytes, offset: int) -> FlexRayFrame: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def DeliveryVtimeNs(self) -> int: ...
  def FrameId(self) -> int: ...
  def CycleCount(self) -> int: ...
  def Channel(self) -> int: ...
  def Flags(self) -> int: ...
  def Data(self, i: int) -> list[int]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
def FlexRayFrameStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FlexRayFrameAddDeliveryVtimeNs(builder: flatbuffers.Builder, deliveryVtimeNs: int) -> None: ...
def FlexRayFrameAddFrameId(builder: flatbuffers.Builder, frameId: int) -> None: ...
def FlexRayFrameAddCycleCount(builder: flatbuffers.Builder, cycleCount: int) -> None: ...
def FlexRayFrameAddChannel(builder: flatbuffers.Builder, channel: int) -> None: ...
def FlexRayFrameAddFlags(builder: flatbuffers.Builder, flags: int) -> None: ...
def FlexRayFrameAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def FlexRayFrameStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def FlexRayFrameEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

