
import typing

import flatbuffers
import numpy as np

from virtmcu.lin.LinMessageType import LinMessageType

type uoffset = flatbuffers.number_types.UOffsetTFlags.py_type

class LinFrame:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> LinFrame: ...
  @classmethod
  def GetRootAsLinFrame(cls, buf: bytes, offset: int) -> LinFrame: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def DeliveryVtimeNs(self) -> int: ...
  def Type(self) -> typing.Literal[LinMessageType.Data, LinMessageType.Break, LinMessageType.Sync]: ...
  def Data(self, i: int) -> list[int]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
def LinFrameStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def LinFrameAddDeliveryVtimeNs(builder: flatbuffers.Builder, deliveryVtimeNs: int) -> None: ...
def LinFrameAddType(builder: flatbuffers.Builder, type: typing.Literal[LinMessageType.Data, LinMessageType.Break, LinMessageType.Sync]) -> None: ...
def LinFrameAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def LinFrameStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def LinFrameEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

