# automatically generated by the FlatBuffers compiler, do not modify

# namespace: lin

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class LinFrame:
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LinFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLinFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # LinFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LinFrame
    def DeliveryVtimeNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # LinFrame
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # LinFrame
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1)
            )
        return 0

    # LinFrame
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # LinFrame
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LinFrame
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0


def LinFrameStart(builder):
    builder.StartObject(3)


def Start(builder):
    LinFrameStart(builder)


def LinFrameAddDeliveryVtimeNs(builder, deliveryVtimeNs):
    builder.PrependUint64Slot(0, deliveryVtimeNs, 0)


def AddDeliveryVtimeNs(builder, deliveryVtimeNs):
    LinFrameAddDeliveryVtimeNs(builder, deliveryVtimeNs)


def LinFrameAddType(builder, type):
    builder.PrependUint8Slot(1, type, 0)


def AddType(builder, type):
    LinFrameAddType(builder, type)


def LinFrameAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)


def AddData(builder, data):
    LinFrameAddData(builder, data)


def LinFrameStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)


def StartDataVector(builder, numElems):
    return LinFrameStartDataVector(builder, numElems)


def LinFrameEnd(builder):
    return builder.EndObject()


def End(builder):
    return LinFrameEnd(builder)
