#!/usr/bin/env python3
"""
scripts/check-stale-so.py

Finds and optionally deletes stale QEMU plugin .so files in the install directory.
A file is considered stale if it doesn't appear in the current modinfo generated by Meson.
"""

import argparse
import logging
import re
import sys
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)


def main() -> int:
    parser = argparse.ArgumentParser(description="Check for stale QEMU plugins.")
    parser.add_argument("--delete", action="store_true", help="Delete stale .so files")
    parser.add_argument("--quiet", action="store_true", help="Suppress non-error output")
    args = parser.parse_args()

    if args.quiet:
        logger.setLevel(logging.WARNING)

    qemu_dir = Path("third_party/qemu")
    if not qemu_dir.exists():
        return 0

    stale_found = False

    for build_dir in qemu_dir.glob("build-virtmcu*"):
        if not build_dir.is_dir():
            continue

        # modinfo-arm-softmmu.c is the ground truth for what QEMU expects to find
        modinfo_file = build_dir / "modinfo-arm-softmmu.c"
        if not modinfo_file.exists():
            continue

        with modinfo_file.open() as f:
            content = f.read()

        # Find all .name = "..." entries
        valid_names = set(re.findall(r'\.name\s*=\s*"([^"]+)"', content))

        # Also find all .objs = ... entries (the QOM types)
        # We don't strictly need them for finding stale .so files, but it helps for diagnostics
        # valid_objs = set(re.findall(r'"([^"]+)",\s*NULL', content))

        # Check in the installation directories
        lib_dirs = [
            build_dir / "install" / "lib" / "aarch64-linux-gnu" / "qemu",
            build_dir / "install" / "lib" / "x86_64-linux-gnu" / "qemu",
            build_dir / "install" / "lib" / "qemu",  # some distros use this
        ]

        for install_lib in lib_dirs:
            if not install_lib.exists():
                continue

            for so_file in install_lib.glob("hw-virtmcu-*.so"):
                name = so_file.stem
                if name not in valid_names:
                    logger.warning(f"Found stale plugin: {so_file}")
                    stale_found = True
                    if args.delete:
                        try:
                            so_file.unlink()
                            logger.info(f"  -> Deleted {so_file.name}")
                        except OSError as e:
                            logger.error(f"  -> Failed to delete {so_file.name}: {e}")
                    else:
                        logger.warning("  -> Run with --delete to remove, or 'make build' to refresh.")

    if stale_found and not args.delete:
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
