import argparse
import re
import sys
from pathlib import Path

TYPE_MAP = {
    "u8": ("B", "uint8_t"),
    "u16": ("H", "uint16_t"),
    "u32": ("I", "uint32_t"),
    "u64": ("Q", "uint64_t"),
    "i8": ("b", "int8_t"),
    "i16": ("h", "int16_t"),
    "i32": ("i", "int32_t"),
    "i64": ("q", "int64_t"),
    "bool": ("?", "bool"),
}

TARGET_STRUCTS = [
    "VirtmcuHandshake",
    "MmioReq",
    "SyscMsg",
    "ClockAdvanceReq",
    "ClockReadyResp",
    "ZenohFrameHeader",
    "ZenohSPIHeader",
]

HEADER = """# =============================================================================
# vproto.py - AUTO-GENERATED BY scripts/gen_vproto.py from hw/rust/virtmcu-api/src/lib.rs — DO NOT EDIT DIRECTLY.
# =============================================================================

import struct
from dataclasses import dataclass
"""


def generate_vproto(rust_src: str) -> str:
    lines = rust_src.splitlines()

    constants = []
    structs = {}

    in_struct = False
    current_struct = None
    current_fields = []

    for line in lines:
        line = line.strip()

        const_match = re.match(r"^pub\s+const\s+([A-Z0-9_]+)\s*:\s*[a-z0-9]+\s*=\s*(.+);$", line)
        if const_match:
            name = const_match.group(1)
            val_str = const_match.group(2)
            val_str = val_str.replace("_", "")
            constants.append((name, val_str))
            continue

        if not in_struct:
            struct_match = re.match(r"^pub\s+struct\s+([A-Za-z0-9_]+)\s*\{$", line)
            if struct_match:
                name = struct_match.group(1)
                if name in TARGET_STRUCTS:
                    in_struct = True
                    current_struct = name
                    current_fields = []
        else:
            if line == "}":
                in_struct = False
                structs[current_struct] = current_fields
                current_struct = None
                current_fields = []
            else:
                # Match simple types: `pub name: u32,`
                field_match = re.match(r"^pub\s+([a-zA-Z0-9_]+)\s*:\s*([a-zA-Z0-9_]+)\s*,?$", line)
                if field_match:
                    fname = field_match.group(1)
                    ftype = field_match.group(2)
                    if fname.endswith("_") and fname != "_":
                        fname = fname[:-1]
                    current_fields.append((fname, ftype))
                    continue
                # Match fixed-size byte arrays: `pub _padding: [u8; N],`
                # Expand [u8; N] into N separate padding bytes so struct sizes match.
                array_match = re.match(r"^pub\s+([a-zA-Z0-9_]+)\s*:\s*\[u8;\s*(\d+)\]\s*,?$", line)
                if array_match:
                    fname = array_match.group(1)
                    count = int(array_match.group(2))
                    for i in range(count):
                        current_fields.append((f"{fname}_{i}", "u8"))

    output = []
    output.append(HEADER)

    for name, val in constants:
        if name in [
            "VIRTMCU_PROTO_MAGIC",
            "VIRTMCU_PROTO_VERSION",
            "MMIO_REQ_READ",
            "MMIO_REQ_WRITE",
            "SYSC_MSG_RESP",
            "SYSC_MSG_IRQ_SET",
            "SYSC_MSG_IRQ_CLEAR",
        ]:
            if val.startswith("0x"):
                output.append(f"{name} = {int(val, 16)}")
            else:
                output.append(f"{name} = {int(val)}")

    output.append("")

    for sname in TARGET_STRUCTS:
        if sname not in structs:
            continue
        fields = structs[sname]

        fmt = "<" + "".join(TYPE_MAP[ftype][0] for _, ftype in fields)
        fmt_name = f"FMT_{camel_to_snake(sname).upper()}"
        size_name = f"SIZE_{camel_to_snake(sname).upper()}"

        output.append(f'{fmt_name} = "{fmt}"')
        output.append(f"{size_name} = struct.calcsize({fmt_name})")
        output.append("")
        output.append("")
        output.append("@dataclass")
        output.append(f"class {sname}:")

        for fname, ftype in fields:
            py_type = "int"
            c_type = TYPE_MAP[ftype][1]
            output.append(f"    {fname}: {py_type}  # {c_type}")

        output.append("")
        output.append("    @classmethod")
        output.append(f'    def unpack(cls, data: bytes) -> "{sname}":')
        output.append(f"        if len(data) != {size_name}:")
        output.append(f'            raise ValueError(f"Expected {{{size_name}}} bytes for {sname}, got {{len(data)}}")')
        output.append(f"        unpacked = struct.unpack({fmt_name}, data)")
        output.append("        return cls(*unpacked)")
        output.append("")
        output.append("    def pack(self) -> bytes:")
        field_list = ", ".join(f"self.{fname}" for fname, _ in fields)
        pack_line = f"        return struct.pack({fmt_name}, {field_list})  # fmt: skip"
        output.append(pack_line)
        output.append("")
        output.append("")

    return "\n".join(output).strip() + "\n"


def camel_to_snake(name):
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Check if tools/vproto.py is up to date")
    args = parser.parse_args()

    rust_file = Path("hw/rust/virtmcu-api/src/lib.rs")
    py_file = Path("tools/vproto.py")

    rust_src = rust_file.read_text(encoding="utf-8")
    generated = generate_vproto(rust_src)

    if args.check:
        current = py_file.read_text(encoding="utf-8")
        if current != generated:
            print("ERROR: tools/vproto.py is out of sync with hw/rust/virtmcu-api/src/lib.rs")
            print("Run 'python3 scripts/gen_vproto.py' to update it.")
            import difflib

            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile="tools/vproto.py",
                tofile="generated",
            )
            sys.stdout.writelines(diff)
            sys.exit(1)
        else:
            print("OK: tools/vproto.py is up to date.")
    else:
        py_file.write_text(generated, encoding="utf-8")
        print(f"Generated {py_file}")


if __name__ == "__main__":
    main()
