#!/usr/bin/env python3
"""
proto_gen.py - Auto-generates Python struct bindings from virtmcu_proto.h

This script ensures that Python consumers of the virtmcu bridge protocols
stay exactly in sync with the C structs, preventing "version drift" and
struct.unpack alignment bugs.
"""

import re
from pathlib import Path

SCRIPT_DIR = Path(Path(__file__).resolve().parent)
PROTO_H_PATH = SCRIPT_DIR.parent / "hw" / "misc" / "virtmcu_proto.h"
OUT_PY_PATH = Path(SCRIPT_DIR) / "vproto.py"

TYPE_MAP = {
    "uint8_t": "B",
    "int8_t": "b",
    "uint16_t": "H",
    "int16_t": "h",
    "uint32_t": "I",
    "int32_t": "i",
    "uint64_t": "Q",
    "int64_t": "q",
}


def parse_header():
    with Path(PROTO_H_PATH).open() as f:
        content = f.read()

    # Extract Defines
    defines = {}
    for match in re.finditer(r"#define\s+([A-Z0-9_]+)\s+([0-9xa-fA-F]+)", content):
        name = match.group(1)
        val = match.group(2)
        if val.startswith("0x"):
            defines[name] = int(val, 16)
        else:
            defines[name] = int(val)

    # Extract Structs
    structs = {}
    struct_pattern = r"struct\s+([a-zA-Z0-9_]+)\s*\{([^}]+)\}\s*__attribute__\(\(packed\)\);"
    for match in re.finditer(struct_pattern, content):
        struct_name = match.group(1)
        body = match.group(2)

        fields = []
        for line in body.split(";"):
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) >= 2:
                c_type = parts[0]
                field_name = parts[1]
                if c_type in TYPE_MAP:
                    fields.append((field_name, TYPE_MAP[c_type], c_type))
        structs[struct_name] = fields

    return defines, structs


def generate_python(defines, structs):
    out = []
    out.append("# =============================================================================")
    out.append("# vproto.py - AUTO-GENERATED BY proto_gen.py")
    out.append("# DO NOT EDIT DIRECTLY. Edit hw/misc/virtmcu_proto.h instead.")
    out.append("# =============================================================================")
    out.append("")
    out.append("import struct")
    out.append("from dataclasses import dataclass")
    out.append("")

    # Emit defines
    for name, val in defines.items():
        out.append(f"{name} = {val}")
    out.append("")

    # Emit structs
    for struct_name, fields in structs.items():
        class_name = "".join(word.capitalize() for word in struct_name.split("_"))

        fmt = "<" + "".join(f[1] for f in fields)
        out.append(f"FMT_{struct_name.upper()} = '{fmt}'")
        out.append(f"SIZE_{struct_name.upper()} = struct.calcsize(FMT_{struct_name.upper()})")
        out.append("")

        out.append("@dataclass")
        out.append(f"class {class_name}:")
        for f_name, _f_fmt, c_type in fields:
            out.append(f"    {f_name}: int  # {c_type}")

        out.append("")
        out.append("    @classmethod")
        out.append(f"    def unpack(cls, data: bytes) -> '{class_name}':")
        out.append(f"        if len(data) != SIZE_{struct_name.upper()}:")
        out.append(
            f'            raise ValueError(f"Expected {{SIZE_{struct_name.upper()}}} bytes for {class_name}, got {{len(data)}}")'
        )
        out.append(f"        unpacked = struct.unpack(FMT_{struct_name.upper()}, data)")
        out.append("        return cls(*unpacked)")
        out.append("")
        out.append("    def pack(self) -> bytes:")
        args = ", ".join(f"self.{f[0]}" for f in fields)
        out.append(f"        return struct.pack(FMT_{struct_name.upper()}, {args})")
        out.append("")

    return "\n".join(out) + "\n"


if __name__ == "__main__":
    defines, structs = parse_header()
    py_code = generate_python(defines, structs)
    with Path(OUT_PY_PATH).open("w") as f:
        f.write(py_code)
    print(f"Generated {OUT_PY_PATH}")
