#!/usr/bin/env python3
"""
proto_gen.py - (LEGACY) Auto-generates Python struct bindings from virtmcu_proto.h

WARNING: This tool is largely obsolete as the project has moved to FlatBuffers.
It remains for reference or for specialized cases where raw C struct packing
is still required. Modern code should use vproto.py and FlatBuffers.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from tools.testing.env import WORKSPACE_DIR

logger = logging.getLogger(__name__)

PROTO_H_PATH = WORKSPACE_DIR / "hw" / "misc" / "virtmcu_proto.h"
OUT_PY_PATH = WORKSPACE_DIR / "tools" / "vproto_legacy.py"

TYPE_MAP = {
    "uint8_t": "B",
    "int8_t": "b",
    "uint16_t": "H",
    "int16_t": "h",
    "uint32_t": "I",
    "int32_t": "i",
    "uint64_t": "Q",
    "int64_t": "q",
}


def parse_header() -> tuple[dict[str, int], dict[str, list[tuple[str, str, str]]]]:
    with Path(PROTO_H_PATH).open() as f:
        content = f.read()

    # Extract Defines
    defines = {}
    for match in re.finditer(r"#define\s+([A-Z0-9_]+)\s+([0-9xa-fA-F]+)", content):
        name = match.group(1)
        val = match.group(2)
        if val.startswith("0x"):
            defines[name] = int(val, 16)
        else:
            defines[name] = int(val)

    # Extract Structs
    structs = {}
    struct_pattern = r"struct\s+([a-zA-Z0-9_]+)\s*\{([^}]+)\}\s*__attribute__\(\(packed\)\);"
    for match in re.finditer(struct_pattern, content):
        struct_name = match.group(1)
        body = match.group(2)

        fields = []
        for line in body.split(";"):
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) >= 2:
                c_type = parts[0]
                field_name = parts[1]
                if c_type in TYPE_MAP:
                    fields.append((field_name, TYPE_MAP[c_type], c_type))
        structs[struct_name] = fields

    return defines, structs


def generate_python(defines: dict[str, int], structs: dict[str, list[tuple[str, str, str]]]) -> str:
    out = []
    out.append("# =============================================================================")
    out.append("# vproto_legacy.py - AUTO-GENERATED BY proto_gen.py")
    out.append("# DO NOT EDIT DIRECTLY. Edit hw/misc/virtmcu_proto.h instead.")
    out.append("# =============================================================================")
    out.append("")
    out.append("")
    out.append("from dataclasses import asdict, dataclass")
    out.append("from dataclasses import fields as dc_fields")
    out.append("")
    out.append("import vproto")
    out.append("")

    # Emit defines
    for name, val in defines.items():
        out.append(f"{name} = {val}")
    out.append("")

    # Emit structs
    for struct_name, fields in structs.items():
        class_name = "".join(word.capitalize() for word in struct_name.split("_"))

        out.append(f"SIZE_{struct_name.upper()} = vproto.SIZE_{struct_name.upper()}")
        out.append("")

        out.append("@dataclass")
        out.append(f"class {class_name}:")
        for f_name, _f_fmt, c_type in fields:
            out.append(f"    {f_name}: int  # {c_type}")

        out.append("")
        out.append("    @classmethod")
        out.append(f"    def unpack(cls, data: bytes) -> {class_name}:")
        out.append(f"        fb_obj = vproto.{class_name}.unpack(data)")
        out.append("        fb_dict = asdict(fb_obj)")
        out.append("        # Filter to only include fields known to this legacy class")
        out.append("        known_fields = {f.name for f in dc_fields(cls)}")
        out.append("        filtered = {k: v for k, v in fb_dict.items() if k in known_fields}")
        out.append("        return cls(**filtered)")
        out.append("")
        out.append("    def pack(self) -> bytes:")
        out.append("        # We initialize the vproto version with our fields.")
        out.append("        # If vproto has extra fields (like quantum_number), they must be handled.")
        out.append(f"        target_cls = vproto.{class_name}")
        out.append("        target_fields = {f.name for f in dc_fields(target_cls)}")
        out.append("        # Filter to only include fields known to target class")
        out.append("        data_dict = {k: v for k, v in asdict(self).items() if k in target_fields}")
        out.append("        # Add missing fields with default 0 if necessary")
        out.append("        for f in target_fields:")
        out.append("            if f not in data_dict:")
        out.append("                data_dict[f] = 0")
        out.append("        return target_cls(**data_dict).pack()")
        out.append("")

    return "\n".join(out) + "\n"


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    defines, structs = parse_header()
    py_code = generate_python(defines, structs)
    with Path(OUT_PY_PATH).open("w") as f:
        f.write(py_code)
    logger.info(f"Generated {OUT_PY_PATH}")
