"""
usd_to_virtmcu.py — Generate C++ address maps from OpenUSD-aligned YAML.

In the cyber-physical bridge (Cyber-Physical Bridge), external simulation tools (like the
MuJoCo bridge or RESD replay) need to know the exact MMIO base addresses of
the virtual peripherals they are communicating with (e.g., the mmio-socket-bridge).

Instead of hardcoding these addresses in C++ and risking a mismatch with the
QEMU Device Tree, this tool parses the single source of truth (the YAML board
description) and emits a C++ header containing `constexpr` base addresses.

Usage:
    python3 usd_to_virtmcu.py <board.yaml> > board_addresses.hpp
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import yaml

#!/usr/bin/env python3

logger = logging.getLogger(__name__)


def parse_yaml(filepath: str | Path) -> None:
    with Path(filepath).open() as f:
        data = yaml.safe_load(f)

    sys.stdout.write(f"/* Generated by usd_to_virtmcu.py from {filepath} */\n")
    sys.stdout.write("#pragma once\n\n")
    sys.stdout.write("#include <cstdint>\n\n")
    sys.stdout.write("namespace virtmcu {\n")
    sys.stdout.write("namespace address_map {\n\n")

    if "peripherals" in data:
        for periph in data["peripherals"]:
            name = periph.get("name", "UNKNOWN")
            addr = periph.get("address", "0x0")
            safe_name = name.replace("-", "_").upper()
            sys.stdout.write(f"    constexpr uint64_t {safe_name}_BASE = {addr};\n")

    sys.stdout.write("\n} // namespace address_map\n")
    sys.stdout.write("} // namespace virtmcu\n")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    if len(sys.argv) < 2:
        logger.error(f"Usage: {sys.argv[0]} <schema.yaml>")
        sys.exit(1)

    parse_yaml(sys.argv[1])
