#!/usr/bin/env python3
"""
usd_to_virtmcu.py — Generate C++ address maps from OpenUSD-aligned YAML.

In the cyber-physical bridge (Phase 10), external simulation tools (like the
MuJoCo bridge or RESD replay) need to know the exact MMIO base addresses of
the virtual peripherals they are communicating with (e.g., the mmio-socket-bridge).

Instead of hardcoding these addresses in C++ and risking a mismatch with the
QEMU Device Tree, this tool parses the single source of truth (the YAML board
description) and emits a C++ header containing `constexpr` base addresses.

Usage:
    python3 usd_to_virtmcu.py <board.yaml> > board_addresses.hpp
"""

import sys
from pathlib import Path

import yaml


def parse_yaml(filepath):
    with Path(filepath).open() as f:
        data = yaml.safe_load(f)

    print(f"/* Generated by usd_to_virtmcu.py from {filepath} */")
    print("#pragma once\n")
    print("#include <cstdint>\n")
    print("namespace virtmcu {")
    print("namespace address_map {\n")

    if "peripherals" in data:
        for periph in data["peripherals"]:
            name = periph.get("name", "UNKNOWN")
            addr = periph.get("address", "0x0")
            safe_name = name.replace("-", "_").upper()
            print(f"    constexpr uint64_t {safe_name}_BASE = {addr};")

    print("\n} // namespace address_map")
    print("} // namespace virtmcu")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <schema.yaml>")
        sys.exit(1)

    parse_yaml(sys.argv[1])
