# =============================================================================
# vproto.py - AUTO-GENERATED BY scripts/gen_vproto.py from hw/rust/virtmcu-api/src/lib.rs — DO NOT EDIT DIRECTLY.
# =============================================================================

import struct
from dataclasses import dataclass

VIRTMCU_PROTO_MAGIC = 1447904085
VIRTMCU_PROTO_VERSION = 1
MMIO_REQ_READ = 0
MMIO_REQ_WRITE = 1
SYSC_MSG_RESP = 0
SYSC_MSG_IRQ_SET = 1
SYSC_MSG_IRQ_CLEAR = 2

FMT_VIRTMCU_HANDSHAKE = "<II"
SIZE_VIRTMCU_HANDSHAKE = struct.calcsize(FMT_VIRTMCU_HANDSHAKE)


@dataclass
class VirtmcuHandshake:
    magic: int  # uint32_t
    version: int  # uint32_t

    @classmethod
    def unpack(cls, data: bytes) -> "VirtmcuHandshake":
        if len(data) != SIZE_VIRTMCU_HANDSHAKE:
            raise ValueError(f"Expected {SIZE_VIRTMCU_HANDSHAKE} bytes for VirtmcuHandshake, got {len(data)}")
        unpacked = struct.unpack(FMT_VIRTMCU_HANDSHAKE, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_VIRTMCU_HANDSHAKE, self.magic, self.version)  # fmt: skip


FMT_MMIO_REQ = "<BBHIQQQ"
SIZE_MMIO_REQ = struct.calcsize(FMT_MMIO_REQ)


@dataclass
class MmioReq:
    type: int  # uint8_t
    size: int  # uint8_t
    reserved1: int  # uint16_t
    reserved2: int  # uint32_t
    vtime_ns: int  # uint64_t
    addr: int  # uint64_t
    data: int  # uint64_t

    @classmethod
    def unpack(cls, data: bytes) -> "MmioReq":
        if len(data) != SIZE_MMIO_REQ:
            raise ValueError(f"Expected {SIZE_MMIO_REQ} bytes for MmioReq, got {len(data)}")
        unpacked = struct.unpack(FMT_MMIO_REQ, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_MMIO_REQ, self.type, self.size, self.reserved1, self.reserved2, self.vtime_ns, self.addr, self.data)  # fmt: skip


FMT_SYSC_MSG = "<IIQ"
SIZE_SYSC_MSG = struct.calcsize(FMT_SYSC_MSG)


@dataclass
class SyscMsg:
    type: int  # uint32_t
    irq_num: int  # uint32_t
    data: int  # uint64_t

    @classmethod
    def unpack(cls, data: bytes) -> "SyscMsg":
        if len(data) != SIZE_SYSC_MSG:
            raise ValueError(f"Expected {SIZE_SYSC_MSG} bytes for SyscMsg, got {len(data)}")
        unpacked = struct.unpack(FMT_SYSC_MSG, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_SYSC_MSG, self.type, self.irq_num, self.data)  # fmt: skip


FMT_CLOCK_ADVANCE_REQ = "<QQ"
SIZE_CLOCK_ADVANCE_REQ = struct.calcsize(FMT_CLOCK_ADVANCE_REQ)


@dataclass
class ClockAdvanceReq:
    delta_ns: int  # uint64_t
    mujoco_time_ns: int  # uint64_t

    @classmethod
    def unpack(cls, data: bytes) -> "ClockAdvanceReq":
        if len(data) != SIZE_CLOCK_ADVANCE_REQ:
            raise ValueError(f"Expected {SIZE_CLOCK_ADVANCE_REQ} bytes for ClockAdvanceReq, got {len(data)}")
        unpacked = struct.unpack(FMT_CLOCK_ADVANCE_REQ, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_CLOCK_ADVANCE_REQ, self.delta_ns, self.mujoco_time_ns)  # fmt: skip


FMT_CLOCK_READY_RESP = "<QII"
SIZE_CLOCK_READY_RESP = struct.calcsize(FMT_CLOCK_READY_RESP)


@dataclass
class ClockReadyResp:
    current_vtime_ns: int  # uint64_t
    n_frames: int  # uint32_t
    error_code: int  # uint32_t

    @classmethod
    def unpack(cls, data: bytes) -> "ClockReadyResp":
        if len(data) != SIZE_CLOCK_READY_RESP:
            raise ValueError(f"Expected {SIZE_CLOCK_READY_RESP} bytes for ClockReadyResp, got {len(data)}")
        unpacked = struct.unpack(FMT_CLOCK_READY_RESP, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_CLOCK_READY_RESP, self.current_vtime_ns, self.n_frames, self.error_code)  # fmt: skip


FMT_ZENOH_FRAME_HEADER = "<QI"
SIZE_ZENOH_FRAME_HEADER = struct.calcsize(FMT_ZENOH_FRAME_HEADER)


@dataclass
class ZenohFrameHeader:
    delivery_vtime_ns: int  # uint64_t
    size: int  # uint32_t

    @classmethod
    def unpack(cls, data: bytes) -> "ZenohFrameHeader":
        if len(data) != SIZE_ZENOH_FRAME_HEADER:
            raise ValueError(f"Expected {SIZE_ZENOH_FRAME_HEADER} bytes for ZenohFrameHeader, got {len(data)}")
        unpacked = struct.unpack(FMT_ZENOH_FRAME_HEADER, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_ZENOH_FRAME_HEADER, self.delivery_vtime_ns, self.size)  # fmt: skip


FMT_ZENOH_SPI_HEADER = "<QI?BBB"
SIZE_ZENOH_SPI_HEADER = struct.calcsize(FMT_ZENOH_SPI_HEADER)


@dataclass
class ZenohSPIHeader:
    delivery_vtime_ns: int  # uint64_t
    size: int  # uint32_t
    cs: int  # bool
    cs_index: int  # uint8_t
    _padding_0: int  # uint8_t
    _padding_1: int  # uint8_t

    @classmethod
    def unpack(cls, data: bytes) -> "ZenohSPIHeader":
        if len(data) != SIZE_ZENOH_SPI_HEADER:
            raise ValueError(f"Expected {SIZE_ZENOH_SPI_HEADER} bytes for ZenohSPIHeader, got {len(data)}")
        unpacked = struct.unpack(FMT_ZENOH_SPI_HEADER, data)
        return cls(*unpacked)

    def pack(self) -> bytes:
        return struct.pack(FMT_ZENOH_SPI_HEADER, self.delivery_vtime_ns, self.size, self.cs, self.cs_index, self._padding_0, self._padding_1)  # fmt: skip
