from __future__ import annotations

# =============================================================================
# vproto_legacy.py - AUTO-GENERATED BY proto_gen.py
# DO NOT EDIT DIRECTLY. Edit hw/misc/virtmcu_proto.h instead.
# =============================================================================
from dataclasses import asdict, dataclass
from dataclasses import fields as dc_fields

from tools import vproto

VIRTMCU_PROTO_MAGIC = 1447904085
VIRTMCU_PROTO_VERSION = 1
MMIO_REQ_READ = 0
MMIO_REQ_WRITE = 1
SYSC_MSG_RESP = 0
SYSC_MSG_IRQ_SET = 1
SYSC_MSG_IRQ_CLEAR = 2

SIZE_VIRTMCU_HANDSHAKE = vproto.SIZE_VIRTMCU_HANDSHAKE


@dataclass
class VirtmcuHandshake:
    magic: int  # uint32_t
    version: int  # uint32_t

    @classmethod
    def unpack(cls, data: bytes) -> VirtmcuHandshake:
        fb_obj = vproto.VirtmcuHandshake.unpack(data)
        fb_dict = asdict(fb_obj)
        # Filter to only include fields known to this legacy class
        known_fields = {f.name for f in dc_fields(cls)}
        filtered = {k: v for k, v in fb_dict.items() if k in known_fields}
        return cls(**filtered)

    def pack(self) -> bytes:
        # We initialize the vproto version with our fields.
        # If vproto has extra fields (like quantum_number), they must be handled.
        target_cls = vproto.VirtmcuHandshake
        target_fields = {f.name for f in dc_fields(target_cls)}
        # Filter to only include fields known to target class
        data_dict = {k: v for k, v in asdict(self).items() if k in target_fields}
        # Add missing fields with default 0 if necessary
        for f in target_fields:
            if f not in data_dict:
                data_dict[f] = 0
        res = target_cls(**data_dict).pack()
        return bytes(res) if res is not None else b""


SIZE_MMIO_REQ = vproto.SIZE_MMIO_REQ


@dataclass
class MmioReq:
    type: int  # uint8_t
    size: int  # uint8_t
    reserved1: int  # uint16_t
    reserved2: int  # uint32_t
    vtime_ns: int  # uint64_t
    addr: int  # uint64_t
    data: int  # uint64_t

    @classmethod
    def unpack(cls, data: bytes) -> MmioReq:
        fb_obj = vproto.MmioReq.unpack(data)
        fb_dict = asdict(fb_obj)
        # Filter to only include fields known to this legacy class
        known_fields = {f.name for f in dc_fields(cls)}
        filtered = {k: v for k, v in fb_dict.items() if k in known_fields}
        return cls(**filtered)

    def pack(self) -> bytes:
        # We initialize the vproto version with our fields.
        # If vproto has extra fields (like quantum_number), they must be handled.
        target_cls = vproto.MmioReq
        target_fields = {f.name for f in dc_fields(target_cls)}
        # Filter to only include fields known to target class
        data_dict = {k: v for k, v in asdict(self).items() if k in target_fields}
        # Add missing fields with default 0 if necessary
        for f in target_fields:
            if f not in data_dict:
                data_dict[f] = 0
        res = target_cls(**data_dict).pack()
        return bytes(res) if res is not None else b""


SIZE_SYSC_MSG = vproto.SIZE_SYSC_MSG


@dataclass
class SyscMsg:
    type: int  # uint32_t
    irq_num: int  # uint32_t
    data: int  # uint64_t

    @classmethod
    def unpack(cls, data: bytes) -> SyscMsg:
        fb_obj = vproto.SyscMsg.unpack(data)
        fb_dict = asdict(fb_obj)
        # Filter to only include fields known to this legacy class
        known_fields = {f.name for f in dc_fields(cls)}
        filtered = {k: v for k, v in fb_dict.items() if k in known_fields}
        return cls(**filtered)

    def pack(self) -> bytes:
        # We initialize the vproto version with our fields.
        # If vproto has extra fields (like quantum_number), they must be handled.
        target_cls = vproto.SyscMsg
        target_fields = {f.name for f in dc_fields(target_cls)}
        # Filter to only include fields known to target class
        data_dict = {k: v for k, v in asdict(self).items() if k in target_fields}
        # Add missing fields with default 0 if necessary
        for f in target_fields:
            if f not in data_dict:
                data_dict[f] = 0
        res = target_cls(**data_dict).pack()
        return bytes(res) if res is not None else b""


SIZE_CLOCK_ADVANCE_REQ = vproto.SIZE_CLOCK_ADVANCE_REQ


@dataclass
class ClockAdvanceReq:
    delta_ns: int  # uint64_t
    mujoco_time_ns: int  # uint64_t

    @classmethod
    def unpack(cls, data: bytes) -> ClockAdvanceReq:
        fb_obj = vproto.ClockAdvanceReq.unpack(data)
        fb_dict = asdict(fb_obj)
        # Filter to only include fields known to this legacy class
        known_fields = {f.name for f in dc_fields(cls)}
        filtered = {k: v for k, v in fb_dict.items() if k in known_fields}
        return cls(**filtered)

    def pack(self) -> bytes:
        # We initialize the vproto version with our fields.
        # If vproto has extra fields (like quantum_number), they must be handled.
        target_cls = vproto.ClockAdvanceReq
        target_fields = {f.name for f in dc_fields(target_cls)}
        # Filter to only include fields known to target class
        data_dict = {k: v for k, v in asdict(self).items() if k in target_fields}
        # Add missing fields with default 0 if necessary
        for f in target_fields:
            if f not in data_dict:
                data_dict[f] = 0
        res = target_cls(**data_dict).pack()
        return bytes(res) if res is not None else b""


SIZE_CLOCK_READY_RESP = vproto.SIZE_CLOCK_READY_RESP


@dataclass
class ClockReadyResp:
    current_vtime_ns: int  # uint64_t
    n_frames: int  # uint32_t
    error_code: int  # uint32_t

    @classmethod
    def unpack(cls, data: bytes) -> ClockReadyResp:
        fb_obj = vproto.ClockReadyResp.unpack(data)
        fb_dict = asdict(fb_obj)
        # Filter to only include fields known to this legacy class
        known_fields = {f.name for f in dc_fields(cls)}
        filtered = {k: v for k, v in fb_dict.items() if k in known_fields}
        return cls(**filtered)

    def pack(self) -> bytes:
        # We initialize the vproto version with our fields.
        # If vproto has extra fields (like quantum_number), they must be handled.
        target_cls = vproto.ClockReadyResp
        target_fields = {f.name for f in dc_fields(target_cls)}
        # Filter to only include fields known to target class
        data_dict = {k: v for k, v in asdict(self).items() if k in target_fields}
        # Add missing fields with default 0 if necessary
        for f in target_fields:
            if f not in data_dict:
                data_dict[f] = 0
        res = target_cls(**data_dict).pack()
        return bytes(res) if res is not None else b""
