#![deny(warnings)]
#![deny(clippy::all)]
#![deny(unused)]

// This test ensures that the `bindings.rs` file generated by `bindgen`
// contains its own internal `#![allow(...)]` attributes.
// If it does not, the `#![deny(warnings)]` at the top of this file
// will cause compilation to fail due to C-style naming, unused code,
// and unnecessary transmutes in the generated bindings.

include!(concat!(env!("OUT_DIR"), "/qemu_bindings.rs"));

#[test]
fn test_bindings_are_self_contained() {
    // Just a dummy test to ensure the module compiles under strict linting
    let _ = core::mem::size_of::<qemu::TypeInfo>();
}
