# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Telemetry

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class TraceEvent:
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TraceEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTraceEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # TraceEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TraceEvent
    def TimestampNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TraceEvent
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TraceEvent
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TraceEvent
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TraceEvent
    def DeviceName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def TraceEventStart(builder):
    builder.StartObject(5)


def Start(builder):
    return TraceEventStart(builder)


def TraceEventAddTimestampNs(builder, timestampNs):
    builder.PrependUint64Slot(0, timestampNs, 0)


def AddTimestampNs(builder, timestampNs):
    return TraceEventAddTimestampNs(builder, timestampNs)


def TraceEventAddType(builder, type):
    builder.PrependInt8Slot(1, type, 0)


def AddType(builder, type):
    return TraceEventAddType(builder, type)


def TraceEventAddId(builder, id):
    builder.PrependUint32Slot(2, id, 0)


def AddId(builder, id):
    return TraceEventAddId(builder, id)


def TraceEventAddValue(builder, value):
    builder.PrependUint32Slot(3, value, 0)


def AddValue(builder, value):
    return TraceEventAddValue(builder, value)


def TraceEventAddDeviceName(builder, deviceName):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(deviceName), 0)


def AddDeviceName(builder, deviceName):
    return TraceEventAddDeviceName(builder, deviceName)


def TraceEventEnd(builder):
    return builder.EndObject()


def End(builder):
    return TraceEventEnd(builder)
