
import typing

import flatbuffers

from Virtmcu.Telemetry.TraceEventType import TraceEventType

type uoffset = flatbuffers.number_types.UOffsetTFlags.py_type

class TraceEvent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TraceEvent: ...
  @classmethod
  def GetRootAsTraceEvent(cls, buf: bytes, offset: int) -> TraceEvent: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TimestampNs(self) -> int: ...
  def Type(self) -> typing.Literal[TraceEventType.CPU_STATE, TraceEventType.IRQ, TraceEventType.PERIPHERAL]: ...
  def Id(self) -> int: ...
  def Value(self) -> int: ...
  def DeviceName(self) -> str | None: ...
def TraceEventStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TraceEventAddTimestampNs(builder: flatbuffers.Builder, timestampNs: int) -> None: ...
def TraceEventAddType(builder: flatbuffers.Builder, type: typing.Literal[TraceEventType.CPU_STATE, TraceEventType.IRQ, TraceEventType.PERIPHERAL]) -> None: ...
def TraceEventAddId(builder: flatbuffers.Builder, id: int) -> None: ...
def TraceEventAddValue(builder: flatbuffers.Builder, value: int) -> None: ...
def TraceEventAddDeviceName(builder: flatbuffers.Builder, deviceName: uoffset) -> None: ...
def TraceEventEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

